SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
 CREATE VIEW [dbo].[AdvCustCommunicationDetail] AS  SELECT * FROM IBL_ENPA_DB_V2.CurDat.AdvCustCommunicationDetail UNION ALL SELECT * FROM IBL_ENPA_DB_V2_2024.DBO.AdvCustCommunicationDetail_2024_Q1 UNION ALL SELECT * FROM IBL_ENPA_DB_V2_2024.DBO.AdvCustCommunicationDetail_2024_Q2 UNION ALL SELECT * FROM IBL_ENPA_DB_V2_2024.DBO.AdvCustCommunicationDetail_2024_Q3 UNION ALL SELECT * FROM IBL_ENPA_DB_V2_2024.DBO.AdvCustCommunicationDetail_2024_Q4
GO