SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO



CREATE PROC [dbo].[MOCFreezeSelectDate]
AS

BEGIN

--SELECT Convert(Varchar(20),EXTDATE,103)EXTDATE FROM SYSDATAMATRIX WHERE EXTDATE=(
--							SELECT EOMONTH(DATE) FROM SYSDAYMATRIX WHERE TIMEKEY=(
--												SELECT MAX(TIMEKEY)+1 FROM SYSDATAMATRIX WHERE MOC_FROZEN='N'
--																)
--	) AND ISNULL(MOC_INITIALISED,'Y')='Y' AND ISNULL(MOC_FROZEN,'N')='N'

	SELECT Convert(Varchar(20),EXTDATE,103) FROM SYSDATAMATRIX WHERE isnull(MOC_FROZEN,'N')='N' and MOC_INITIALISED='Y'




END


GO