SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
  
  
  
/*=========================================  
 AUTHER : TRILOKIKHANNA  
 CREATE DATE : 27-11-2019  
 MODIFY DATE : 27-11-2019  
 DESCRIPTION : Calculation Reference Period WITH HELPOF REFPERIOD  
 --EXEC [pro].[Reference_Period_Calculation] @TIMEKEY=26372   
=============================================*/  
CREATE PROCEDURE [PRO].[Reference_Period_Calculation]   
@TIMEKEY INT  
AS  
BEGIN  
       SET NOCOUNT ON  
    BEGIN TRY  
      
  
/*   -- BELOW CODE COMMENTED - Because AS PER DISCUSSIONS ASSET NOT WILL BE USED FROM ACCOUNT SOURCE DATA  
UPDATE PRO.RefPeriod SET LogicSql='UPDATE A SET  A.RefPeriodoverdue    = '+CAST(RefValue AS varchar)+',A.RefPeriodOverDrawn  = '+CAST(RefValue AS VARCHAR)+',A.RefPeriodNoCredit     = '+CAST(RefValue AS varchar)+',A.RefPeriodIntService = '+CAST(RefValue AS
 varchar)+'  
FROM PRO.ACCOUNTCAL A INNER JOIN DimProduct B ON A.ProductAlt_Key=B.ProductAlt_Key and B.EffectiveFromTimeKey<='+cast(@TIMEKEY as varchar)+' AND B.EffectiveToTimeKey>='+cast(@TIMEKEY as varchar)+'  AND B.ProductSubGroup=''AGRI366'''    
WHERE BusinessRule='RefPeriodAgr366'   
  
*/  
    
UPDATE PRO.ACCOUNTCAL   
SET   
REFPERIODOVERDUE=0,  
REFPERIODOVERDRAWN=0,  
REFPERIODNOCREDIT=0,  
REFPERIODINTSERVICE=0,  
REFPERIODSTKSTATEMENT=0,  
REFPERIODREVIEW=0  
  
  
  
--IF OBJECT_ID('TEMPDB..#TEMPTABLE') IS NOT NULL  
--DROP TABLE #TEMPTABLE  
  
--SELECT IDENTITY(INT,1,1) ID ,LOGICSQL INTO #TEMPTABLE FROM PRO.REFPERIOD   
--WHERE (LOGICSQL IS NOT NULL AND LOGICSQL<>'') and EffectiveFromTimeKey<=@TIMEKEY AND EffectiveToTimeKey>=@TIMEKEY order by Rule_Key   
  
     
--DECLARE @START INT=1 ,@TOTALCOUNT INT=(SELECT COUNT(1) FROM #TEMPTABLE)  
--DECLARE @RESULT VARCHAR(MAX)  
--WHILE(@START<=@TOTALCOUNT)  
--BEGIN  
--  SET @RESULT=(SELECT LOGICSQL FROM #TEMPTABLE WHERE ID=@START)  
--  EXEC (@RESULT)  
    
--  SET @START=@START+1  
  
--END  
  
UPDATE A SET A.REFPERIODOVERDUE =(SELECT TOP 1 REFVALUE FROM PRO.REFPERIOD WHERE BUSINESSRULE = 'REFPERIODOVERDUE' AND EFFECTIVEFROMTIMEKEY<=@TIMEKEY AND EFFECTIVETOTIMEKEY>=@TIMEKEY)  
FROM PRO.ACCOUNTCAL A   
UPDATE A SET A.REFPERIODOVERDRAWN   =(SELECT TOP 1 REFVALUE FROM PRO.REFPERIOD WHERE BUSINESSRULE = 'REFPERIODOVERDRAWN' AND EFFECTIVEFROMTIMEKEY<=@TIMEKEY AND EFFECTIVETOTIMEKEY>=@TIMEKEY)  
FROM PRO.ACCOUNTCAL A   
UPDATE A SET A.REFPERIODNOCREDIT  =(SELECT TOP 1 REFVALUE FROM PRO.REFPERIOD WHERE BUSINESSRULE = 'REFPERIODNOCREDIT' AND EFFECTIVEFROMTIMEKEY<=@TIMEKEY AND EFFECTIVETOTIMEKEY>=@TIMEKEY)  
FROM PRO.ACCOUNTCAL A   
UPDATE A SET A.REFPERIODINTSERVICE   =(SELECT TOP 1 REFVALUE FROM PRO.REFPERIOD WHERE BUSINESSRULE = 'REFPERIODINTSERVICE' AND EFFECTIVEFROMTIMEKEY<=@TIMEKEY AND EFFECTIVETOTIMEKEY>=@TIMEKEY)  
FROM PRO.ACCOUNTCAL A   
UPDATE A SET A.REFPERIODSTKSTATEMENT  =(SELECT TOP 1 REFVALUE FROM PRO.REFPERIOD WHERE BUSINESSRULE = 'REFPERIODSTKSTATEMENT' AND EFFECTIVEFROMTIMEKEY<=@TIMEKEY AND EFFECTIVETOTIMEKEY>=@TIMEKEY)  
FROM PRO.ACCOUNTCAL A   
UPDATE A SET A.REFPERIODREVIEW  =(SELECT TOP 1 REFVALUE FROM PRO.REFPERIOD WHERE BUSINESSRULE = 'REFPERIODREVIEW' AND EFFECTIVEFROMTIMEKEY<=@TIMEKEY AND EFFECTIVETOTIMEKEY>=@TIMEKEY)  
FROM PRO.ACCOUNTCAL A   
  
 UPDATE PRO.ACLRUNNINGPROCESSSTATUS   
 SET COMPLETED='Y',ERRORDATE=NULL,ERRORDESCRIPTION=NULL,COUNT=ISNULL(COUNT,0)+1  
 WHERE RUNNINGPROCESSNAME='Reference_Period_Calculation'  
  
 -----------------Added for DashBoard 04-03-2021  
Update BANDAUDITSTATUS set CompletedCount=CompletedCount+1 where BandName='ASSET CLASSIFICATION'  
  
END TRY  
BEGIN  CATCH  
  
 UPDATE PRO.ACLRUNNINGPROCESSSTATUS   
 SET COMPLETED='N',ERRORDATE=GETDATE(),ERRORDESCRIPTION=ERROR_MESSAGE(),COUNT=ISNULL(COUNT,0)+1  
 WHERE RUNNINGPROCESSNAME='Reference_Period_Calculation'  
END CATCH  
 SET NOCOUNT OFF  
  
END  
  
  
  
GO