SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

/*=======================================
AUTHER : TRILOKI KHANNA
CREATE DATE : 27-11-2019
MODIFY DATE : 27-11-2019
DESCRIPTION : MARKING OF IN MONTH MARK AT CUSTOMER LEVEL
--EXEC [PRO].[Marking_InMonthMark_Customer_Account_level]  @timekey=25140
=============================================*/
CREATE PROCEDURE [PRO].[Marking_InMonthMark_Customer_Account_level]
@TIMEKEY INT
WITH RECOMPILE
AS
BEGIN
  SET NOCOUNT ON
 BEGIN TRY
 
DECLARE @PROCESSDATE DATE=(SELECT Date FROM SysDayMatrix WHERE  TimeKey=@timekey)
DECLARE @PROC_FREQ CHAR(1)=(select RefValue from PRO.RefPeriod WHERE BusinessRule='PROC_FREQ' )
DECLARE @PROC_CONDITION decimal=(select CAST(RefValue AS decimal(18,2)) from PRO.RefPeriod WHERE BusinessRule='PROC_CONDITION')

UPDATE PRO.CUSTOMERCAL SET INMONTHMARK='N' 

IF @PROC_FREQ='D' AND @PROCESSDATE<>EOMONTH(@PROCESSDATE)
BEGIN

UPDATE A SET A.INMONTHMARK='Y'
FROM  PRO.CUSTOMERCAL A INNER JOIN PRO.AccountCal B  ON A.SourceSystemCustomerID=B.SourceSystemCustomerID


UPDATE PRO.CUSTOMERCAL SET INMONTHMARK='N' WHERE (INMONTHMARK IS NULL)


END
ELSE 
UPDATE A SET A.INMONTHMARK= 'Y' FROM  PRO.CUSTOMERCAL A



	UPDATE PRO.ACLRUNNINGPROCESSSTATUS 
	SET COMPLETED='Y',ERRORDATE=NULL,ERRORDESCRIPTION=NULL,COUNT=ISNULL(COUNT,0)+1
	WHERE RUNNINGPROCESSNAME='Marking_InMonthMark_Customer_Account_level'

	-----------------Added for DashBoard 04-03-2021
--Update BANDAUDITSTATUS set CompletedCount=CompletedCount+1 where BandName='ASSET CLASSIFICATION'

END TRY
BEGIN  CATCH

	UPDATE PRO.ACLRUNNINGPROCESSSTATUS 
	SET COMPLETED='N',ERRORDATE=GETDATE(),ERRORDESCRIPTION=ERROR_MESSAGE(),COUNT=ISNULL(COUNT,0)+1
	WHERE RUNNINGPROCESSNAME='Marking_InMonthMark_Customer_Account_level'

END CATCH

 SET NOCOUNT OFF
END












GO