SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

/*=========================================
 AUTHER : TRILOKI KHANNA
 CREATE DATE : 30-12-2019
 MODIFY DATE : 31-12-2019
 DESCRIPTION :UPDATE NPA TYPE AT ACCOUNT LEVEL
 EXEC [PRO].[UPDATE_NPA_TYPE] 4925
=============================================*/
CREATE PROCEDURE [PRO].[UPDATE_NPA_TYPE]
@TIMEKEY INT
AS
BEGIN
/*----------------Update NpaType in account cal table ---------------------------- */

UPDATE A SET 	A.NpaType = ( CASE	 
										WHEN CD=5 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 90 AND  119  THEN  'REGULAR'
										WHEN CD=6 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 120 AND  149  THEN  'REGULAR'
										WHEN CD=7 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 150 AND  179  THEN  'REGULAR'
										WHEN CD=8 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 180 AND  209  THEN  'REGULAR'
										WHEN CD=9 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX >=210  THEN  'REGULAR'

										WHEN CD=5 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 90 AND   119  THEN  'REGULAR'
										WHEN CD=6 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 120 AND  149  THEN  'REGULAR'
										WHEN CD=7 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 150 AND  179  THEN  'REGULAR'
										WHEN CD=8 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 180 AND  209  THEN  'REGULAR'
										WHEN CD=9 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX >=210  THEN  'REGULAR'

										WHEN CD=5 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 90 AND   119  THEN  'REGULAR'
										WHEN CD=6 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 120 AND  149  THEN  'REGULAR'
										WHEN CD=7 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 150 AND  179  THEN  'REGULAR'
										WHEN CD=8 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 180 AND  209  THEN  'REGULAR'
										WHEN CD=9 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX >=210  THEN  'REGULAR'

										WHEN CD=5 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 90 AND   119  THEN  'REGULAR'
										WHEN CD=6 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 120 AND  149  THEN  'REGULAR'
										WHEN CD=7 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 150 AND  179  THEN  'REGULAR'
										WHEN CD=8 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 180 AND  209  THEN  'REGULAR'
										WHEN CD=9 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX >=210  THEN  'REGULAR'

										WHEN CD=2 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 1 AND  29   THEN  'STICKY'
										WHEN CD=3 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 30 AND  59  THEN  'STICKY'
										WHEN CD=4 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 60 AND  89  THEN  'STICKY'

										WHEN CD=2 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 1 AND  29   THEN  'STICKY'
										WHEN CD=3 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 30 AND  59  THEN  'STICKY'
										WHEN CD=4 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 60 AND  89  THEN  'STICKY'

										WHEN CD=2 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 1 AND  29   THEN  'STICKY'
										WHEN CD=3 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 30 AND  59  THEN  'STICKY'
										WHEN CD=4 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 60 AND  89  THEN  'STICKY'

										WHEN CD=2 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 1 AND  29   THEN  'STICKY'
										WHEN CD=3 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 30 AND  59  THEN  'STICKY'
										WHEN CD=4 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 60 AND  89  THEN  'STICKY'

										WHEN CD=0 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX =0   THEN  'MULTIPLE'
										WHEN CD=1 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX=0   THEN  'MULTIPLE'
										WHEN CD=2 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 1 AND  29   THEN  'MULTIPLE'
										WHEN CD=3 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 30 AND  59   THEN  'MULTIPLE'
										WHEN CD=4 AND DA.ASSETCLASSSHORTNAME='SUB' AND DPD_MAX BETWEEN 60 AND  89   THEN  'MULTIPLE'

										WHEN CD=0 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX =0   THEN  'MULTIPLE'
										WHEN CD=1 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX=0   THEN  'MULTIPLE'
										WHEN CD=2 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 1 AND  29   THEN  'MULTIPLE'
										WHEN CD=3 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 30 AND  59   THEN  'MULTIPLE'
										WHEN CD=4 AND DA.ASSETCLASSSHORTNAME='DB1' AND DPD_MAX BETWEEN 60 AND  89   THEN  'MULTIPLE'
										
										WHEN CD=0 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX =0   THEN  'MULTIPLE'
										WHEN CD=1 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX=0   THEN  'MULTIPLE'
										WHEN CD=2 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 1 AND  29   THEN  'MULTIPLE'
										WHEN CD=3 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 30 AND  59   THEN  'MULTIPLE'
										WHEN CD=4 AND DA.ASSETCLASSSHORTNAME='DB2' AND DPD_MAX BETWEEN 60 AND  89   THEN  'MULTIPLE'

										WHEN CD=0 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX =0   THEN  'MULTIPLE'
										WHEN CD=1 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX=0   THEN  'MULTIPLE'
										WHEN CD=2 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 1 AND  29   THEN  'MULTIPLE'
										WHEN CD=3 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 30 AND  59   THEN  'MULTIPLE'
										WHEN CD=4 AND DA.ASSETCLASSSHORTNAME='DB3' AND DPD_MAX BETWEEN 60 AND  89   THEN  'MULTIPLE'

								 END	
						      )					 
FROM pro.AccountCal A INNER JOIN DimSourceDB B ON A.SourceAlt_Key=B.SourceAlt_Key
     AND (B.EffectiveFromTimeKey<=@TIMEKEY AND B.EffectiveToTimeKey>=@TIMEKEY)
INNER JOIN DimAssetClass DA ON A.FinalAssetClassAlt_Key=DA.AssetClassAlt_Key
     AND (DA.EffectiveFromTimeKey<=@TIMEKEY AND DA.EffectiveToTimeKey>=@TIMEKEY)
WHERE B.SourceName='VisionPLUS'  AND DA.AssetClassGroup='NPA'

END

GO