SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO



CREATE FUNCTION [dbo].[D2K_Split](@String nvarchar(MAX), @Delimiter char(1))
RETURNS @Results TABLE (SNO INT IDENTITY (1,1),Items nvarchar(MAX))
AS


BEGIN
DECLARE @INDEX INT
DECLARE @SLICE nvarchar(MAX)
-- HAVE TO SET TO 1 SO IT DOESNT EQUAL Z
--     ERO FIRST TIME IN LOOP
SELECT @INDEX = 1
-- following line added 10/06/04 as null
--      values cause issues
IF @String IS NULL RETURN
WHILE @INDEX !=0

BEGIN
-- GET THE INDEX OF THE FIRST OCCURENCE OF THE SPLIT CHARACTER
SELECT @INDEX = CHARINDEX(@Delimiter,rtrim(ltrim(@STRING)))
-- NOW PUSH EVERYTHING TO THE LEFT OF IT INTO THE SLICE VARIABLE
IF @INDEX !=0
SELECT @SLICE = LEFT(rtrim(ltrim(@STRING)),@INDEX - 1)
ELSE
SELECT @SLICE = rtrim(ltrim(@STRING))
-- PUT THE ITEM INTO THE RESULTS SET
INSERT INTO @Results(Items) VALUES(@SLICE)
-- CHOP THE ITEM REMOVED OFF THE MAIN STRING
SELECT @STRING = RIGHT(@STRING,LEN(rtrim(ltrim(@STRING))) - @INDEX)
-- BREAK OUT IF WE ARE DONE
IF LEN(@STRING) = 0 BREAK
END
RETURN
END

GO