CREATE TABLE [CurDat].[BuyoutDetails_Final] (
  [Entity_Key] [bigint] NULL,
  [SummaryID] [int] NULL,
  [SlNo] [int] NULL,
  [ReferenceNo] [varchar](30) NULL,
  [PoolName] [varchar](50) NULL,
  [Category] [varchar](50) NULL,
  [BuyoutPartyLoanNo] [varchar](20) NULL,
  [CustomerName] [varchar](100) NULL,
  [PAN] [varchar](10) NULL,
  [AadharNo] [varchar](12) NULL,
  [PrincipalOutstanding] [decimal](18, 2) NULL,
  [InterestReceivable] [decimal](18, 2) NULL,
  [Charges] [decimal](18, 2) NULL,
  [AccuredInterest] [decimal](18, 2) NULL,
  [DPD] [int] NULL,
  [AssetClass] [varchar](50) NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [Changes] [varchar](200) NULL,
  [Remark] [varchar](200) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [date] NULL,
  [ModifyBy] [varchar](100) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [date] NULL,
  [SecurityValue] [decimal](18, 2) NULL,
  [FinalNpaDt] [date] NULL,
  [FinalAssetClassAlt_Key] [smallint] NULL,
  [ProvisionAlt_Key] [smallint] NULL,
  [NetBalance] [decimal](18, 2) NULL,
  [ApprRV] [decimal](18, 2) NULL,
  [SecuredAmt] [decimal](18, 2) NULL,
  [UnSecuredAmt] [decimal](18, 2) NULL,
  [UsedRV] [decimal](18, 2) NULL,
  [Provsecured] [decimal](18, 2) NULL,
  [ProvUnsecured] [decimal](18, 2) NULL,
  [TotalProvision] [decimal](18, 2) NULL,
  [FLGDEG] [char](1) NULL,
  [FLGUPG] [char](1) NULL,
  [DegReason] [varchar](500) NULL,
  [UpgDate] [date] NULL,
  [PrevProvPercentage] [decimal](16, 2) NULL,
  [FinalProvPercentage] [decimal](16, 2) NULL,
  [MainCustomer] [varchar](100) NULL,
  [NPADate] [date] NULL,
  [InterestOverdue] [decimal](16, 2) NULL,
  [DailyInterestAccrualAmount] [decimal](16, 2) NULL,
  [InterestSuspendedAmount] [decimal](16, 2) NULL,
  [SuspendedInterestAmount] [decimal](16, 2) NULL,
  [BuyOutEntityID] [int] NOT NULL,
  [ModifiedBy] [varchar](15) NULL,
  [CustomerACID] [varchar](50) NULL,
  [AccountName] [varchar](80) NULL,
  [NPAReason] [varchar](max) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO