CREATE TABLE [CurDat].[AdvCustNpaDetail] (
  [ENTITYKEY] [bigint] NOT NULL,
  [CustomerEntityId] [int] NOT NULL,
  [Cust_AssetClassAlt_Key] [smallint] NULL,
  [NPADt] [date] NULL,
  [LastInttChargedDt] [date] NULL,
  [DbtDt] [date] NULL,
  [LosDt] [date] NULL,
  [DefaultReason1Alt_Key] [smallint] NULL,
  [DefaultReason2Alt_Key] [smallint] NULL,
  [StaffAccountability] [char](1) NULL,
  [LastIntBooked] [date] NULL,
  [RefCustomerID] [varchar](20) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [date] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [date] NULL,
  [D2Ktimestamp] [datetime] NOT NULL,
  [MocStatus] [char](1) NULL,
  [MocDate] [date] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [NPA_Reason] [varchar](1000) NULL,
  CONSTRAINT [AdvCustNPADetail_AccountEntityID] PRIMARY KEY NONCLUSTERED ([CustomerEntityId], [EffectiveFromTimeKey], [EffectiveToTimeKey]),
  CHECK ([EffectiveToTimeKey]=(49999)),
  CHECK ([EffectiveToTimeKey]=(49999)),
  CHECK ([EffectiveToTimeKey]=(49999))
)
ON [PRIMARY]
GO