CREATE TABLE [CurDat].[AdvAcRestructureDetail_PIRAMAL_MISDB] (
  [EntityKey] [bigint] NOT NULL,
  [AccountEntityId] [int] NULL,
  [RestructureTypeAlt_Key] [smallint] NULL,
  [RestructureProposalDt] [date] NULL,
  [RestructureDt] [date] NULL,
  [RestructureAmt] [decimal] NULL,
  [RestructureApprovalDt] [date] NULL,
  [RestructureSequenceRefNo] [int] NULL,
  [DiminutionAmount] [decimal] NULL,
  [RestructureByAlt_Key] [int] NULL,
  [RefCustomerId] [varchar](20) NULL,
  [RefSystemAcId] [varchar](30) NULL,
  [SDR_INVOKED] [char](1) NULL,
  [SDR_REFER_DATE] [date] NULL,
  [Remark] [varchar](250) NULL,
  [RestructureFacilityTypeAlt_Key] [smallint] NULL,
  [BankingRelationTypeAlt_Key] [smallint] NULL,
  [InvocationDate] [date] NULL,
  [AssetClassAlt_KeyOnInvocation] [smallint] NULL,
  [EquityConversionYN] [char](1) NULL,
  [ConversionDate] [date] NULL,
  [PrincRepayStartDate] [date] NULL,
  [InttRepayStartDate] [date] NULL,
  [PreRestructureAssetClassAlt_Key] [smallint] NULL,
  [PreRestructureNPA_Date] [date] NULL,
  [ProvPerOnRestrucure] [decimal](5, 2) NULL,
  [COVID_OTR_CatgAlt_Key] [smallint] NULL,
  [RestructureApprovingAuthority] [varchar](50) NULL,
  [RestructreTOS] [decimal](20, 2) NULL,
  [UnserviceInttAsOnRestructure] [decimal](20, 2) NULL,
  [RestructurePOS] [decimal](20, 2) NULL,
  [RestructureStage] [varchar](50) NULL,
  [RestructureStatus] [smallint] NULL,
  [DPD_AsOnRestructure] [smallint] NULL,
  [DPD_Breach_Date] [date] NULL,
  [ZeroDPD_Date] [date] NULL,
  [SurvPeriodEndDate] [date] NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [binary](8) NOT NULL,
  [RestructureFailureDate] [date] NULL,
  [UpgradeDate] [date] NULL,
  [PreDegProvPer] [decimal](5, 2) NULL,
  [SP_ExpiryExtendedDate] [date] NULL,
  [ChangeField] [text] NULL,
  [RestructureDescription] [text] NULL,
  [InvestmentGrade] [char](1) NULL,
  [POS_10PerPaidDate] [date] NULL,
  [FlgMorat] [char](1) NULL,
  [PreRestructureNPA_Prov] [decimal](5, 2) NULL,
  [RestructureAssetClassAlt_key] [int] NULL,
  [PostRestrucAssetClass] [int] NULL,
  [RestructureCatgAlt_Key] [smallint] NULL,
  [BankingType] [int] NULL,
  [COVID_OTR_Catg] [varchar](10) NULL,
  [Is_COVID_Morat] [varchar](5) NULL,
  [Is_InvestmentGrade] [varchar](20) NULL,
  [RevisedBusinessSegment] [varchar](30) NULL,
  [PreRestrucNPA_Date] [datetime] NULL,
  [DisbursementDate] [date] NULL,
  [PreRestrucDefaultDate] [datetime] NULL,
  [Npa_Qtr] [varchar](20) NULL,
  [RestructureDate] [date] NULL,
  [ApprovingAuthAlt_Key] [varchar](50) NULL,
  [RepaymentStartDate] [date] NULL,
  [IntRepayStartDate] [datetime] NULL,
  [RefDate] [datetime] NULL,
  [IsEquityCoversion] [char](1) NULL,
  [FstDefaultReportingBank] [varchar](50) NULL,
  [ICA_SignDate] [datetime] NULL,
  [CreditProvision] [decimal](16, 2) NULL,
  [DFVProvision] [decimal](16, 2) NULL,
  [MTMProvision] [decimal](16, 2) NULL,
  [CRILIC_Fst_DefaultDate] [datetime] NULL,
  [RevisedBusSegAlt_Key] [int] NULL,
  [NPA_Provision_per] [decimal](16, 2) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO