CREATE TABLE [CurDat].[AdvAcRestructureDetail] (
  [EntityKey] [bigint] NOT NULL,
  [AccountEntityId] [int] NULL,
  [RestructureTypeAlt_Key] [smallint] NULL,
  [RestructureCatgAlt_Key] [smallint] NULL,
  [RestructureProposalDt] [date] NULL,
  [RestructureDt] [date] NULL,
  [RestructureAmt] [decimal] NULL,
  [ApprovingAuthAlt_Key] [varchar](10) NULL,
  [RestructureApprovalDt] [date] NULL,
  [RestructureSequenceRefNo] [int] NULL,
  [DiminutionAmount] [decimal] NULL,
  [RestructureByAlt_Key] [int] NULL,
  [RefCustomerId] [varchar](20) NULL,
  [RefSystemAcId] [varchar](30) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [CDRFlg] [char](1) NULL,
  [ExitCDRFlg] [char](1) NULL,
  [CutOffDate] [date] NULL,
  [RepaymentStartDate] [date] NULL,
  [RestructureReason] [char](3) NULL,
  [OverDueSinceDt] [date] NULL,
  [BankApprovalDt] [date] NULL,
  [ForwardDt] [date] NULL,
  [Remark] [varchar](250) NULL,
  [SDR_INVOKED] [char](1) NULL,
  [SDR_REFER_DATE] [date] NULL,
  [PreRestrucDefaultDate] [datetime] NULL,
  [PreRestrucAssetClass] [int] NULL,
  [PreRestrucNPA_Date] [datetime] NULL,
  [PostRestrucAssetClass] [int] NULL,
  [IntRepayStartDate] [datetime] NULL,
  [RefDate] [datetime] NULL,
  [InvocationDate] [datetime] NULL,
  [IsEquityCoversion] [char](1) NULL,
  [ConversionDate] [datetime] NULL,
  [Is_COVID_Morat] [varchar](5) NULL,
  [COVID_OTR_Catg] [varchar](10) NULL,
  [CRILIC_Fst_DefaultDate] [datetime] NULL,
  [FstDefaultReportingBank] [varchar](50) NULL,
  [ICA_SignDate] [datetime] NULL,
  [Is_InvestmentGrade] [varchar](20) NULL,
  [CreditProvision] [decimal](16, 2) NULL,
  [DFVProvision] [decimal](16, 2) NULL,
  [MTMProvision] [decimal](16, 2) NULL,
  [RevisedBusinessSegment] [varchar](30) NULL,
  [BankingType] [int] NULL,
  [DisbursementDate] [date] NULL,
  [RestructureAssetClassAlt_key] [int] NULL,
  [RestructureDate] [date] NULL,
  [Npa_QtrAlt_Key] [varchar](20) NULL,
  [RestructurePOS] [decimal](16, 2) NULL,
  [RevisedBusSegAlt_Key] [int] NULL,
  [SP_ExpiryDate] [date] NULL,
  [FlgPUI] [char](1) NULL,
  [NEW_SP_PERIOD_EXP_DATE] [date] NULL,
  [RESTR_STATUS] [varchar](30) NULL,
  [POST_DEG_DEFAULT] [char](1) NULL,
  [POST_DEG_DEFAULT_DATE] [date] NULL,
  [DEFAULT_IN_MONITORING_PERIOD] [char](1) NULL,
  [POST_RESTR_UPG_DATE] [date] NULL,
  [DPD_AsOnRestr] [smallint] NULL,
  [SLBC_Restructuring] [char](1) NULL,
  [Npa_Qtr] [varchar](20) NULL,
  [AccountBusinessSegmentCode] [int] NULL,
  [SLBCRestructuring] [char](1) NULL,
  [NPAIdentificationdate] [varchar](20) NULL,
  [DPDdtrestructuring] [varchar](20) NULL,
  [ProvPerOnRestrucure] [decimal](5, 2) NULL,
  [RestructureDateII] [date] NULL,
  [PreRF2AssetClassAtl_Key] [smallint] NULL,
  [DPD_30_90_Breach_Date] [date] NULL,
  [FlgRestrActive] [char](1) NULL,
  [RF2_CODE] [varchar](10) NULL,
  [USFB_RestCategory] [varchar](10) NULL,
  [TEN_PC_DATE] [date] NULL
)
ON [PRIMARY]
GO