CREATE TABLE [CurDat].[DerivativeDetail] (
  [EntityKey] [bigint] IDENTITY,
  [DerivativeEntityID] [int] NOT NULL,
  [CustomerACID] [varchar](30) NULL,
  [CustomerID] [varchar](30) NULL,
  [CustomerName] [varchar](100) NULL,
  [DerivativeRefNo] [varchar](30) NULL,
  [Duedate] [date] NULL,
  [DueAmt] [decimal](16, 2) NULL,
  [OsAmt] [decimal](16, 2) NULL,
  [POS] [decimal](16, 2) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](100) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [smalldatetime] NULL,
  [DateofData] [date] NULL,
  [SourceSystem] [varchar](30) NULL,
  [BranchCode] [varchar](10) NULL,
  [UCIC_ID] [varchar](20) NULL,
  [FLGDEG] [char](1) NULL,
  [DEGREASON] [varchar](500) NULL,
  [DPD] [int] NULL,
  [FLGUPG] [char](1) NULL,
  [UpgDate] [date] NULL,
  [DBTDate] [date] NULL,
  [PROVISIONALT_KEY] [int] NULL,
  [InitialAssetAlt_Key] [int] NULL,
  [InitialNPIDt] [date] NULL,
  [DPD_DivOverdue] [int] NULL,
  [FinalAssetClassAlt_Key] [int] NULL,
  [NPIDt] [date] NULL,
  [AssetClass_AltKey] [smallint] NULL,
  [TotalProvison] [decimal](18, 2) NULL,
  [InstrumentName] [varchar](30) NULL,
  [OverDueSinceDt] [date] NULL,
  [DueAmtReceivable] [decimal](18, 2) NULL,
  [MTMIncomeAmt] [decimal](18, 2) NULL,
  [CouponDate] [date] NULL,
  [CouponAmt] [decimal](18, 2) NULL,
  [CouponOverDueSinceDt] [date] NULL,
  [OverdueCouponAmt] [decimal](18, 2) NULL,
  [DPD_CouponOverDue] [int] NULL,
  [ChangeFields] [varchar](250) NULL,
  [FlgSMA] [char](1) NULL,
  [SMA_Dt] [date] NULL,
  [SMA_Class] [varchar](5) NULL,
  [SMA_Reason] [varchar](1000) NULL,
  [AddlProvision] [decimal](18, 2) NULL,
  [AddlProvisionPer] [decimal](5, 2) NULL,
  [FlgMoc] [char](1) NULL,
  [MocBy] [varchar](20) NULL,
  [MOC_Date] [date] NULL,
  [MOC_Reason] [varchar](100) NULL,
  [Asset_Norm] [varchar](10) NULL,
  CONSTRAINT [DerivativeDetail_DerivativeEntityID] PRIMARY KEY NONCLUSTERED ([DerivativeEntityID], [EffectiveFromTimeKey], [EffectiveToTimeKey])
)
ON [PRIMARY]
GO