CREATE TABLE [CurDat].[AdvAcFinancialDetail] (
  [ENTITYKEY] [bigint] NOT NULL,
  [AccountEntityId] [int] NOT NULL,
  [Ac_LastReviewDueDt] [date] NULL,
  [Ac_ReviewTypeAlt_key] [smallint] NULL,
  [Ac_ReviewDt] [date] NULL,
  [Ac_ReviewAuthAlt_Key] [smallint] NULL,
  [Ac_NextReviewDueDt] [date] NULL,
  [DrawingPower] [decimal](16, 2) NULL,
  [InttRate] [decimal](4, 2) NULL,
  [NpaDt] [date] NULL,
  [BookDebts] [decimal](14) NULL,
  [UnDrawnAmt] [decimal](14) NULL,
  [UnAdjSubSidy] [decimal](14) NULL,
  [LastInttRealiseDt] [date] NULL,
  [MocStatus] [varchar](10) NULL,
  [MOCReason] [smallint] NULL,
  [LimitDisbursed] [decimal](14) NULL,
  [RefCustomerId] [varchar](20) NULL,
  [RefSystemAcId] [varchar](30) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [datetime] NOT NULL,
  [MocDate] [smalldatetime] NULL,
  [MocTypeAlt_Key] [int] NULL,
  [CropDuration] [smallint] NULL,
  [Ac_ReviewAuthLevelAlt_Key] [smallint] NULL,
  [AccountBlkCode2] [varchar](20) NULL,
  CONSTRAINT [AdvAcFinancialDetail_AccountEntityID] PRIMARY KEY NONCLUSTERED ([AccountEntityId], [EffectiveFromTimeKey], [EffectiveToTimeKey]),
  CHECK ([EffectiveToTimeKey]=(49999))
)
ON [PRIMARY]
GO