CREATE TABLE [dbo].[CustomerMissingMOC] (
  [Entity_Key] [int] IDENTITY,
  [CustomerID] [varchar](50) NULL,
  [CustomerName] [varchar](100) NULL,
  [CustomerEntityID] [int] NULL,
  [AssetClass] [varchar](20) NULL,
  [AssetClassAlt_Key] [int] NULL,
  [NPADate] [date] NULL,
  [SecurityValue] [decimal](18, 2) NULL,
  [AdditionalProvision] [decimal](16, 2) NULL,
  [FraudAccountFlagAlt_Key] [int] NULL,
  [FraudDate] [date] NULL,
  [MOCTypeAlt_Key] [int] NULL,
  [MOCType] [varchar](50) NULL,
  [MOCReason] [varchar](100) NULL,
  [MOCDate] [date] NULL,
  [MOCBy] [varchar](50) NULL,
  [DateOfDate] [date] NULL,
  [Level1ApprovedBy] [varchar](50) NULL,
  [Level2ApprovedBy] [varchar](50) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [CreatedBy] [varchar](50) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [varchar](50) NULL,
  [DateApproved] [datetime] NULL,
  [MOCSourceAltkey] [int] NULL,
  [ScreenFlag] [char](1) NULL,
  [ApprovedByFirstLevel] [varchar](100) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [SrNo] [int] NULL,
  [UploadID] [int] NULL,
  [MOCSource] [varchar](50) NULL,
  [ModifyBy] [varchar](100) NULL,
  [ChangeField] [varchar](max) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO