CREATE TABLE [dbo].[SysReportDirectory] (
  [SeqNo] [smallint] NULL,
  [ReportID] [varchar](max) NULL,
  [ReportType] [varchar](50) NULL,
  [ReportRdlName] [varchar](max) NULL,
  [ReportUrl] [varchar](max) NULL,
  [VersionNo] [varchar](max) NULL,
  [Remark] [varchar](max) NULL,
  [DeploymentDt] [date] NULL,
  [Frequency_Period] [varchar](50) NULL,
  [Deploy] [char](3) NULL,
  [Deploy_Prod] [char](3) NULL,
  [ReportMenuId] [int] NULL,
  [ReportRdlFullName] [varchar](max) NULL,
  [ReportFieldDisplay] [nvarchar](20) NULL,
  [DeptReportNo] [varchar](20) NULL,
  [RBI_ReportNo] [varchar](50) NULL,
  [CRisMacReportNo] [varchar](50) NULL,
  [ReportFrequency_Key] [smallint] NULL,
  [ReportingDay] [varchar](30) NULL,
  [ReportOwnerMain] [varchar](20) NULL,
  [ReportOwnerAlternate] [varchar](50) NULL,
  [SubmissionType] [varchar](50) NULL,
  [FirstReportGenerationDate] [date] NULL,
  [NextEntityCreationDate] [date] NULL,
  [DaysToGenerate] [smallint] NULL,
  [AdvReminderInDays] [smallint] NULL,
  [AdvReminderRecipient] [varchar](50) NULL,
  [AdvReminderCopyTo] [varchar](500) NULL,
  [AdvReminderSubject] [varchar](100) NULL,
  [AdvReminderText] [varchar](500) NULL,
  [Reminder1_InDays] [smallint] NULL,
  [Reminder1_Recipient] [varchar](50) NULL,
  [Reminder1_CopyTo] [varchar](500) NULL,
  [Reminder1_Subject] [varchar](100) NULL,
  [Reminder1_Text] [varchar](500) NULL,
  [Reminder2_InDays] [smallint] NULL,
  [Reminder2_Recipient] [varchar](50) NULL,
  [Reminder2_CopyTo] [varchar](500) NULL,
  [Reminder2_Subject] [varchar](100) NULL,
  [Reminder2_Text] [varchar](500) NULL,
  [RBI_Recipient] [varchar](50) NULL,
  [RBI_CopyTo] [varchar](500) NULL,
  [RBI_Subject] [varchar](100) NULL,
  [RBI_Text] [varchar](500) NULL,
  [Monitoring_Required] [char](1) NULL,
  [Ch_RptFrequency_EffectiveDate] [date] NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifyBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [ExportReportId] [varchar](max) NULL,
  [ExportReportName] [varchar](max) NULL,
  [DeptGroupId] [smallint] NULL,
  [PreMoc] [char](1) NULL,
  [ReqCommonSelecton] [char](1) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO