CREATE TABLE [dbo].[AdvAcRestructureDetail_Mod] (
  [EntityKey] [int] IDENTITY,
  [AccountEntityId] [int] NULL,
  [RestructureTypeAlt_Key] [smallint] NULL,
  [RestructureCatgAlt_Key] [smallint] NULL,
  [RestructureProposalDt] [date] NULL,
  [RestructureAmt] [decimal] NULL,
  [RestructureApprovalDt] [date] NULL,
  [RestructureSequenceRefNo] [int] NULL,
  [DiminutionAmount] [decimal] NULL,
  [RestructureByAlt_Key] [int] NULL,
  [RefCustomerId] [varchar](20) NULL,
  [RefSystemAcId] [varchar](30) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [OverDueSinceDt] [date] NULL,
  [BankApprovalDt] [date] NULL,
  [ForwardDt] [date] NULL,
  [Remark] [varchar](250) NULL,
  [ChangeFields] [varchar](100) NULL,
  [PreRestrucDefaultDate] [datetime] NULL,
  [PreRestrucAssetClass] [int] NULL,
  [PostRestrucAssetClass] [int] NULL,
  [InvocationDate] [datetime] NULL,
  [ConversionDate] [datetime] NULL,
  [CRILIC_Fst_DefaultDate] [datetime] NULL,
  [FstDefaultReportingBank] [varchar](50) NULL,
  [ICA_SignDate] [datetime] NULL,
  [CreditProvision] [decimal](16, 2) NULL,
  [DFVProvision] [decimal](16, 2) NULL,
  [MTMProvision] [decimal](16, 2) NULL,
  [DisbursementDate] [date] NULL,
  [RestructurePOS] [decimal](16, 2) NULL,
  [Restructure_NPA_Dt] [date] NULL,
  [RestructureDt] [date] NULL,
  [BankingRelationTypeAlt_Key] [int] NULL,
  [EquityConversionYN] [varchar](20) NULL,
  [PrincRepayStartDate] [date] NULL,
  [InttRepayStartDate] [datetime] NULL,
  [PreRestructureAssetClassAlt_Key] [int] NULL,
  [PreRestructureNPA_Date] [datetime] NULL,
  [COVID_OTR_CatgAlt_Key] [varchar](10) NULL,
  [RestructureApprovingAuthority] [varchar](10) NULL,
  [InvestmentGrade] [varchar](20) NULL,
  [FlgMorat] [varchar](5) NULL,
  [PreRestructureNPA_Prov] [decimal](16, 2) NULL,
  [StatusofSpecificPeriod] [varchar](max) NULL,
  CONSTRAINT [PK_AdvAcRestructureDetail1] PRIMARY KEY NONCLUSTERED ([EntityKey]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO