CREATE TABLE [dbo].[BuyoutFinalDetails] (
  [Entity_Key] [int] IDENTITY,
  [SummaryID] [int] NULL,
  [SlNo] [int] NULL,
  [CIFId] [varchar](max) NULL,
  [ENBDAcNo] [varchar](max) NULL,
  [BuyoutPartyLoanNo] [varchar](max) NULL,
  [PartnerDPD] [varchar](max) NULL,
  [PartnerDPDAsOnDate] [datetime] NULL,
  [PartnerAssetClass] [varchar](max) NULL,
  [PartnerNPADate] [datetime] NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [Changes] [varchar](200) NULL,
  [Remark] [varchar](200) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [date] NULL,
  [ModifyBy] [varchar](100) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [date] NULL,
  [SecurityValue] [decimal](18, 2) NULL,
  [FinalNpaDt] [date] NULL,
  [FinalAssetClassAlt_Key] [smallint] NULL,
  [ProvisionAlt_Key] [smallint] NULL,
  [NetBalance] [decimal](18, 2) NULL,
  [ApprRV] [decimal](18, 2) NULL,
  [SecuredAmt] [decimal](18, 2) NULL,
  [UnSecuredAmt] [decimal](18, 2) NULL,
  [UsedRV] [decimal](18, 2) NULL,
  [Provsecured] [decimal](18, 2) NULL,
  [ProvUnsecured] [decimal](18, 2) NULL,
  [TotalProvision] [decimal](18, 2) NULL,
  [FLGDEG] [char](1) NULL,
  [FLGUPG] [char](1) NULL,
  [DegReason] [varchar](500) NULL,
  [UpgDate] [date] NULL,
  [PrevProvPercentage] [decimal](16, 2) NULL,
  [FinalProvPercentage] [decimal](16, 2) NULL,
  [Action] [char](1) NULL,
  [AddlProvision] [decimal](16, 2) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO