CREATE TABLE [dbo].[RP_Portfolio_Upload_Mod] (
  [EntityKey] [int] IDENTITY,
  [CustomerEntityID] [int] NULL,
  [UCIC_ID] [varchar](20) NULL,
  [CustomerID] [varchar](20) NULL,
  [PAN_No] [varchar](12) NULL,
  [CustomerName] [varchar](100) NULL,
  [BankCode] [varchar](20) NULL,
  [BorrowerDefaultDate] [datetime] NULL,
  [LeadBankName] [varchar](100) NULL,
  [DefaultStatus] [varchar](100) NULL,
  [ImplementationStatus] [varchar](100) NULL,
  [Actual_Impl_Date] [datetime] NULL,
  [RP_OutOfDateAllBanksDeadline] [datetime] NULL,
  [ChangeFields] [varchar](100) NULL,
  [Remarks] [varchar](100) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [CreatedBy] [varchar](50) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](50) NULL,
  [DateApproved] [smalldatetime] NULL,
  [ReportingBank_LenderCode] [varchar](80) NULL,
  [BankArrangementDesc] [varchar](200) NULL,
  [ExposureBucket] [varchar](100) NULL,
  [RefrenceDate] [date] NULL,
  [ICAStatus] [varchar](20) NULL,
  [NotSigingICAReason] [varchar](250) NULL,
  [ICAExecutionDate] [date] NULL,
  [NatureRPApprovalDate] [date] NULL,
  [RPNature] [varchar](200) NULL,
  [OtherRPNature] [varchar](500) NULL,
  [IBCFilingDate] [date] NULL,
  [IBCAddmissionDate] [date] NULL,
  [StatusOfRevisedRPDeadline] [varchar](20) NULL,
  [SrNo] [int] NULL,
  [UploadID] [int] NULL,
  [ApprovedByFirstLevel] [varchar](100) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [BorrowerPAN] [varchar](15) NULL,
  [ChangeField] [varchar](max) NULL,
  [IfRPisRectificationthenRiskReviewTimeline] [datetime] NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO