CREATE TABLE [dbo].[ACL_NPA_DATA] (
  [Generation Date] [nvarchar](30) NULL,
  [Process_Date] [nvarchar](30) NULL,
  [UCIC] [varchar](50) NULL,
  [CustomerID] [varchar](50) NULL,
  [CustomerName] [varchar](225) NULL,
  [Branchcode] [varchar](20) NULL,
  [CustomerAcid] [varchar](30) NULL,
  [Facilitytype] [varchar](10) NULL,
  [ProductCode] [varchar](20) NULL,
  [ProductName] [varchar](200) NULL,
  [Balance] [decimal](16, 2) NULL,
  [DrawingPower] [decimal](16, 2) NULL,
  [CurrentLimit] [decimal](16, 2) NULL,
  [UnAppliedIntt] [decimal](18, 2) NULL,
  [ReviewDueDt] [date] NULL,
  [CreditSinceDt] [date] NULL,
  [ContiExcessDt] [date] NULL,
  [StockStDt] [date] NULL,
  [DebitSinceDt] [date] NULL,
  [LastCrDate] [date] NULL,
  [PreQtrCredit] [decimal](16, 2) NULL,
  [PrvQtrInt] [decimal](16, 2) NULL,
  [CurQtrCredit] [decimal](16, 2) NULL,
  [CurQtrInt] [decimal](16, 2) NULL,
  [OverdueAmt] [decimal](18, 2) NULL,
  [OverDueSinceDt] [date] NULL,
  [SecurityValue] [decimal](24) NULL,
  [NetBalance] [decimal](16, 2) NULL,
  [PrincOutStd] [decimal](18, 2) NULL,
  [ApprRV] [decimal](22, 2) NULL,
  [SecuredAmt] [decimal](16, 2) NULL,
  [UnSecuredAmt] [decimal](16, 2) NULL,
  [Provsecured] [decimal](16, 2) NULL,
  [ProvUnsecured] [decimal](16, 2) NULL,
  [TotalProvision] [decimal](16, 2) NULL,
  [RefPeriodOverdue] [smallint] NULL,
  [RefPeriodOverDrawn] [smallint] NULL,
  [RefPeriodNoCredit] [smallint] NULL,
  [RefPeriodIntService] [smallint] NULL,
  [RefPeriodStkStatement] [smallint] NULL,
  [RefPeriodReview] [smallint] NULL,
  [PrincOverdue] [decimal](18, 2) NULL,
  [PrincOverdueSinceDt] [date] NULL,
  [IntOverdue] [decimal](18, 2) NULL,
  [IntOverdueSinceDt] [date] NULL,
  [OtherOverdue] [decimal](18, 2) NULL,
  [OtherOverdueSinceDt] [date] NULL,
  [DPD_IntService] [int] NULL,
  [DPD_NoCredit] [int] NULL,
  [DPD_Overdrawn] [int] NULL,
  [DPD_Overdue] [int] NULL,
  [DPD_Renewal] [int] NULL,
  [DPD_StockStmt] [int] NULL,
  [DPD_PrincOverdue] [int] NULL,
  [DPD_IntOverdueSince] [int] NULL,
  [DPD_OtherOverdueSince] [int] NULL,
  [DPD_Max] [int] NULL,
  [InitialNpaDt] [date] NULL,
  [FinalNpaDt] [date] NULL,
  [InitialAssetClassAlt_Key] [int] NULL,
  [InitialAssetClass] [varchar](20) NULL,
  [FinalAssetClassAlt_Key] [int] NULL,
  [FialAssetClass] [varchar](20) NULL,
  [DegReason] [varchar](max) NULL,
  [FlgDeg] [char](1) NULL,
  [FlgUpg] [char](1) NULL,
  [NPA_Reason] [varchar](max) NULL,
  [SecuredFlag] [char](1) NULL,
  [Asset_Norm] [varchar](15) NULL,
  [CD] [varchar](20) NULL,
  [NPANorms] [varchar](20) NULL,
  [WriteOffAmount] [decimal](16, 2) NULL,
  [ActSegmentCode] [varchar](10) NULL,
  [ProductSubGroup] [varchar](50) NULL,
  [SourceName] [varchar](50) NULL,
  [ProductGroup] [varchar](50) NULL,
  [SchemeType] [varchar](20) NULL,
  [AcBuRevisedSegmentCode] [varchar](20) NULL,
  [DegDate] [date] NULL,
  [MOC_Dt] [date] NULL,
  [MOCReason] [varchar](500) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO