CREATE TABLE [dbo].[InvestmentFinancialDetail_mod] (
  [EntityKey] [bigint] IDENTITY,
  [InvEntityId] [int] NOT NULL,
  [RefInvID] [varchar](100) NULL,
  [RefIssuerID] [varchar](100) NULL,
  [HoldingNature] [char](3) NULL,
  [CurrencyAlt_Key] [tinyint] NULL,
  [CurrencyConvRate] [decimal](12, 4) NULL,
  [BookType] [varchar](25) NULL,
  [BookValue] [decimal](18, 2) NULL,
  [BookValueINR] [decimal](18, 2) NULL,
  [MTMValue] [decimal](18, 2) NULL,
  [MTMValueINR] [decimal](18, 2) NULL,
  [EncumberedMTM] [decimal](18, 2) NULL,
  [AssetClass_AltKey] [tinyint] NULL,
  [NPIDt] [date] NULL,
  [TotalProvison] [decimal](18, 2) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](100) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [smalldatetime] NULL,
  [DBTDate] [date] NULL,
  [LatestBSDate] [date] NULL,
  [Interest_DividendDueDate] [date] NULL,
  [Interest_DividendDueAmount] [decimal](16, 2) NULL,
  [PartialRedumptionDueDate] [date] NULL,
  [PartialRedumptionSettledY_N] [char](1) NULL,
  [changefields] [varchar](100) NULL,
  [FLGDEG] [char](1) NULL,
  [DEGREASON] [varchar](50) NULL,
  [DPD] [varchar](20) NULL,
  [FLGUPG] [char](1) NULL,
  [UpgDate] [varchar](20) NULL
)
ON [PRIMARY]
GO