CREATE TABLE [dbo].[DimGLProduct] (
  [GLProduct_Key] [smallint] NOT NULL,
  [GLProductAlt_Key] [smallint] NOT NULL,
  [GLCode] [varchar](20) NULL,
  [GLName] [varchar](200) NULL,
  [ProductCode] [varchar](10) NULL,
  [ProductName] [varchar](200) NULL,
  [GLType] [varchar](10) NULL,
  [GLSta] [varchar](10) NULL,
  [GLGroup] [varchar](10) NULL,
  [FacilityType] [varchar](10) NULL,
  [FacilitySubType] [varchar](10) NULL,
  [ExpType] [smallint] NULL,
  [Bsr1aCode] [varchar](6) NULL,
  [RetailGL] [smallint] NULL,
  [SrcSysModule] [varchar](10) NULL,
  [SancFacilityType] [varchar](10) NULL,
  [AssetClassGrp] [varchar](4) NULL,
  [LcIssued] [char](1) NULL,
  [CIBILCreditType] [varchar](4) NULL,
  [NewFacilityAllowed] [char](1) NULL,
  [GovGurCover] [smallint] NULL,
  [AssetClass] [varchar](20) NULL,
  [ApplicableSubSector] [varchar](200) NULL,
  [RepaySingleBullet] [char](1) NULL,
  [CashFlowEnable] [char](1) NULL,
  [RepayAllowFreq] [varchar](10) NULL,
  [GLProductValidCode] [char](1) NULL,
  [SrcSysGLCode] [varchar](50) NULL,
  [SrcSysGLName] [varchar](200) NULL,
  [DestSysGLProductAdvTypeCode] [varchar](10) NULL,
  [DestSysGLProductCode] [varchar](10) NULL,
  [EI_Scheme_Flag] [char](1) NULL,
  [GLAdvGrp] [varchar](20) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [timestamp],
  [CIBIL_ConsumerAcType] [char](2) NULL,
  [AcTypeAlt_Key] [varchar](100) NULL
)
ON [PRIMARY]
GO