CREATE TABLE [dbo].[RestructureAsset_Upload_Mod] (
  [AccountID] [varchar](50) NULL,
  [AccountEntityID] [int] NULL,
  [UploadID] [int] NULL,
  [RestructureFacility] [varchar](100) NULL,
  [RevisedBusinessSeg] [varchar](50) NULL,
  [DisbursementDate] [date] NULL,
  [ReferenceDate] [date] NULL,
  [InvocationDate] [date] NULL,
  [DateofConversionintoEquity] [date] NULL,
  [PrinRpymntStartDate] [date] NULL,
  [InttRpymntStartDate] [date] NULL,
  [AssetClassatRstrctr] [varchar](50) NULL,
  [IfNPANPADate] [date] NULL,
  [NPAQuarter] [varchar](20) NULL,
  [TypeofRestructuring] [varchar](50) NULL,
  [CovidMoratoriamMSME] [varchar](50) NULL,
  [CovidOTRCategory] [varchar](50) NULL,
  [BankingRelationship] [varchar](50) NULL,
  [DateofRestructuring] [date] NULL,
  [RestructuringApprovingAuth] [varchar](50) NULL,
  [DateofIstDefaultonCRILIC] [date] NULL,
  [ReportingBank] [varchar](50) NULL,
  [DateofSigningICA] [date] NULL,
  [InvestmentGrade] [varchar](50) NULL,
  [CreditProvisionRs] [decimal](18, 2) NULL,
  [DFVProvisionRs] [decimal](18, 2) NULL,
  [MTMProvisionRs] [decimal](18, 2) NULL,
  [SheetName] [varchar](255) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [SrNo] [int] NULL,
  [OSasonDateofRstrctr] [decimal](18, 2) NULL,
  [POSasonDateofRstrctr] [decimal](18, 2) NULL,
  [approvedbyfirstlevel] [varchar](100) NULL,
  [DateApprovedByFirstLevel] [date] NULL,
  [EquityConversion] [varchar](10) NULL,
  [StatusOfSpecificPeriod] [varchar](max) NULL,
  [NPAIdentificationDate] [date] NULL,
  [DPD_AsOnRestr] [smallint] NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO