CREATE TABLE [dbo].[DimNPAProvision_Mod] (
  [EntityKey] [int] IDENTITY,
  [ProvisionAlt_Key] [int] NULL,
  [Segment] [varchar](20) NULL,
  [ProvisionRule] [varchar](20) NULL,
  [SecurityApplicable] [varchar](1) NULL,
  [ProductAlt_Key] [varchar](20) NULL,
  [ProvisionName] [varchar](255) NULL,
  [ProvisionShortNameEnum] [varchar](255) NULL,
  [ProvisionSecured] [decimal](5, 2) NULL,
  [ProvisionUnSecured] [decimal](5, 2) NULL,
  [LowerDPD] [int] NULL,
  [UpperDPD] [int] NULL,
  [DB1_PROV] [decimal] NULL,
  [DB2_PROV] [decimal] NULL,
  [ProvProductCat] [varchar](255) NULL,
  [RBIProvisionSecured] [decimal] NULL,
  [RBIProvisionUnSecured] [decimal] NULL,
  [AdditionalprovisionRBINORMS] [varchar](30) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [ChangeFields] [varchar](500) NULL,
  [Remarks] [varchar](500) NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [CreatedBy] [varchar](50) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [varchar](50) NULL,
  [DateApproved] [datetime] NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [ApprovedByFirstLevel] [varchar](20) NULL
)
ON [PRIMARY]
GO