CREATE TABLE [dbo].[MetaScreenFieldDetail] (
  [EntityKey] [int] IDENTITY,
  [MenuId] [smallint] NULL,
  [ScreenName] [varchar](50) NULL,
  [CtrlName] [varchar](100) NULL,
  [ResourceKey] [varchar](150) NULL,
  [FldDataType] [varchar](20) NULL,
  [Col_lg] [varchar](2) NULL,
  [Col_md] [varchar](2) NULL,
  [Col_sm] [varchar](2) NULL,
  [MinLength] [smallint] NULL,
  [MaxLength] [smallint] NULL,
  [ErrorCheck] [char](1) NULL,
  [DataSeq] [smallint] NULL,
  [FldGridView] [varchar](2) NULL,
  [CriticalErrorType] [varchar](2) NULL,
  [ScreenFieldNo] [int] NULL,
  [IsEditable] [char](1) NULL,
  [IsVisible] [char](1) NULL,
  [IsUpper] [char](1) NULL,
  [IsMandatory] [char](1) NULL,
  [AllowChar] [varchar](50) NULL,
  [DisAllowChar] [varchar](50) NULL,
  [DefaultValue] [varchar](50) NULL,
  [AllowToolTip] [char](1) NULL,
  [ReferenceColumnName] [varchar](80) NULL,
  [ReferenceTableName] [varchar](80) NULL,
  [MOC_Flag] [char](1) NULL,
  [UserID] [varchar](20) NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [datetime] NULL,
  [ScreenFieldGroup] [char](2) NULL,
  [HigherLevelEdit] [char](1) NULL,
  [ApplicableForWorkFlow] [char](1) NULL,
  [IsExtractedEditable] [char](1) NULL,
  [IsMocVisible] [char](1) NULL
)
ON [PRIMARY]
GO