CREATE TABLE [dbo].[MOC_PROV_REPORT_DATA] (
  [Report Date] [nvarchar](30) NULL,
  [UCIC] [varchar](50) NULL,
  [CIF ID] [varchar](50) NULL,
  [Borrower Name] [varchar](8000) NULL,
  [Branch Code] [varchar](20) NULL,
  [Branch Name] [varchar](8000) NULL,
  [Account No.] [varchar](30) NULL,
  [Source System] [varchar](50) NULL,
  [Facility] [varchar](10) NULL,
  [Scheme Type] [varchar](20) NULL,
  [Scheme Code] [varchar](20) NULL,
  [Scheme Description] [varchar](200) NULL,
  [Secured/Unsecured] [varchar](9) NOT NULL,
  [Seg Code] [varchar](30) NULL,
  [Segment Description] [varchar](100) NULL,
  [Business Segment] [varchar](20) NULL,
  [Account DPD] [int] NULL,
  [Cycle Past due] [varchar](20) NULL,
  [NPA Date] [date] NULL,
  [Asset Classification] [varchar](50) NULL,
  [NPA Norms] [smallint] NULL,
  [Balance Outstanding] [decimal](16, 2) NULL,
  [Customer Security Value] [decimal](18, 2) NULL,
  [Security Value Appropriated] [decimal](22, 2) NULL,
  [Secured Outstanding] [decimal](16, 2) NULL,
  [Unsecured Outstanding] [decimal](16, 2) NULL,
  [Provision Total] [decimal](16, 2) NULL,
  [Provision Secured] [decimal](16, 2) NULL,
  [Provision Unsecured] [decimal](16, 2) NULL,
  [Net NPA] [decimal](17, 2) NOT NULL,
  [ProvisionSecured%] [decimal](5, 2) NULL,
  [ProvisionUnSecured%] [decimal](5, 2) NULL,
  [ProvisionTotal%] [decimal](5, 2) NULL,
  [Prev. Qtr. Balance Outstanding] [decimal](16, 2) NOT NULL,
  [Prev. Qtr. Secured Outstanding] [decimal](16, 2) NOT NULL,
  [Prev. Qtr. Unsecured Outstanding] [decimal](16, 2) NOT NULL,
  [Prev. Qtr.Provision Total] [decimal](16, 2) NOT NULL,
  [Prev. Qtr.Provision Secured] [decimal](16, 2) NOT NULL,
  [Prev. Qtr. Provision Unsecured] [decimal](16, 2) NOT NULL,
  [Prev. Qtr. Net NPA] [decimal](17, 2) NOT NULL,
  [NPAIncrease] [decimal](17, 2) NOT NULL,
  [NPADecrease] [decimal](17, 2) NOT NULL,
  [ProvisionIncrease] [decimal](17, 2) NOT NULL,
  [ProvisionDecrease] [decimal](17, 2) NOT NULL,
  [NetNPAIncrease] [decimal](18, 2) NOT NULL,
  [NetNPAnDecrease] [decimal](18, 2) NOT NULL
)
ON [PRIMARY]
GO