CREATE TABLE [dbo].[DimActivity] (
  [Activity_Key] [smallint] NOT NULL,
  [ActivityAlt_Key] [smallint] NOT NULL,
  [ActivityName] [varchar](100) NULL,
  [ActivityShortName] [varchar](20) NULL,
  [ActivityShortNameEnum] [varchar](20) NULL,
  [ActivityGroup] [varchar](50) NULL,
  [ActivitySubGroup] [varchar](50) NULL,
  [ActivitySegment] [varchar](50) NULL,
  [ActivityValidCode] [char](1) NULL,
  [IndustryAlt_Key] [smallint] NULL,
  [BSR1Acode] [varchar](5) NULL,
  [BSR1Bcode] [varchar](3) NULL,
  [FoodPro] [smallint] NULL,
  [ActivityLBRCode] [char](2) NULL,
  [AssetClass] [varchar](20) NULL,
  [BSR3code] [varchar](10) NULL,
  [CIBIL_ConsumerAcType] [varchar](2) NULL,
  [ComodityCode] [varchar](10) NULL,
  [SectorLBRCode] [varchar](2) NULL,
  [SickIndustryCode] [varchar](6) NULL,
  [SickSSIIndAlt_Key] [smallint] NULL,
  [AssetClassNorm] [varchar](50) NULL,
  [OtherAssets] [char](1) NULL,
  [MinorActivity] [char](1) NULL,
  [SHGActivity] [char](1) NULL,
  [Prod] [char](1) NULL,
  [Inv] [char](1) NULL,
  [NF] [char](1) NULL,
  [Act_Type] [varchar](20) NULL,
  [LBRGroup] [varchar](50) NULL,
  [LBRSubGroup] [varchar](50) NULL,
  [LBRCode] [smallint] NULL,
  [Act_PH] [varchar](10) NULL,
  [CIBILBusinessIndustryType] [varchar](10) NULL,
  [SICCode] [varchar](20) NULL,
  [ActivitySubGroupDescription] [varchar](100) NULL,
  [Intrest_Freq] [varchar](10) NULL,
  [SrcSysActivityCode] [varchar](50) NULL,
  [SrcSysActivityCode1] [varchar](50) NULL,
  [SrcSysActivityName] [varchar](255) NULL,
  [SrcSysActivityName1] [varchar](100) NULL,
  [DestSysActivityCode] [varchar](10) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModifie] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [timestamp],
  [VCI] [char](1) NULL,
  [IRBMark] [varchar](20) NULL,
  [EWSIndustryAlt_Key] [smallint] NULL,
  [BSEIndustryAlt_Key] [smallint] NULL,
  [EWSKeySectorAlt_Key] [int] NULL,
  [NewActivitySegment] [varchar](50) NULL,
  [Allied_Agr] [char](1) NULL
)
ON [PRIMARY]
GO