CREATE TABLE [dbo].[ReversefeedCalypso] (
  [EntityKey] [int] IDENTITY,
  [CalypsoRFEntityID] [int] NULL,
  [Date_of_data] [date] NULL,
  [source_system_name] [varchar](30) NULL,
  [branch_code] [varchar](64) NULL,
  [ucic_id] [varchar](64) NULL,
  [issuerId] [varchar](8000) NULL,
  [issuuerName] [varchar](256) NULL,
  [Ref_Txn_Sys_Cust_ID] [varchar](256) NULL,
  [PAN] [varchar](64) NULL,
  [ISSUER_CATEGORY_CODE] [varchar](64) NULL,
  [GrpEntityOfBank] [varchar](256) NULL,
  [CP_HOLIDAY] [varchar](20) NULL,
  [CP_EXTERNAL_REF] [varchar](64) NULL,
  [CP_FINANCIAL] [varchar](20) NULL,
  [CP_PARENT] [varchar](256) NULL,
  [CP_COMMENT] [varchar](256) NULL,
  [CP_STATUS] [varchar](64) NULL,
  [COUNTERPARTY_SHORTNAME] [varchar](256) NULL,
  [COUNTERPARTY_FULLNAME] [varchar](256) NULL,
  [COUNTERPARTY_ROLE1] [varchar](64) NULL,
  [COUNTERPARTY_COUNTRY] [varchar](64) NULL,
  [COUNTERPARTY_ROLE2] [varchar](64) NULL,
  [COUNTERPARTY_ROLE3] [varchar](64) NULL,
  [COUNTERPARTY_ROLE4] [varchar](64) NULL,
  [COUNTERPARTY_ROLE5] [varchar](64) NULL,
  [CIF_ID] [varchar](64) NULL,
  [ENPA_ASSET_CODE] [varchar](64) NULL,
  [ENPA_DESCRIPTION] [varchar](64) NULL,
  [ENPA_ASSET_CODE_DATE] [varchar](64) NULL,
  [ENPA_D2K_NPA_DATE] [varchar](64) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](100) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [smalldatetime] NULL,
  [IsChanged] [char](1) NULL
)
ON [PRIMARY]
GO