CREATE TABLE [dbo].[DimGL] (
  [GL_Key] [smallint] IDENTITY,
  [GLAlt_Key] [smallint] NOT NULL,
  [GLCode] [varchar](20) NULL,
  [GLName] [varchar](200) NULL,
  [GLShortName] [varchar](20) NULL,
  [GLShortNameEnum] [varchar](20) NULL,
  [GLGroupType] [varchar](50) NULL,
  [GLGroupAlt_Key] [int] NULL,
  [GLGroup] [varchar](50) NULL,
  [GLSubGroupAlt_Key] [int] NULL,
  [GLSubGroup] [varchar](50) NULL,
  [GLSegmentAlt_Key] [int] NULL,
  [GLSegment] [varchar](200) NULL,
  [GLSubSegment] [varchar](50) NULL,
  [GLValidCode] [char](1) NULL,
  [AbstractCat] [varchar](20) NULL,
  [AbstractCode] [varchar](20) NULL,
  [AbstractDescription] [varchar](50) NULL,
  [AdvRefGLAlt_key] [int] NULL,
  [BsDescription] [varchar](100) NULL,
  [BsSchedule] [smallint] NULL,
  [BsScheduleDescription] [varchar](80) NULL,
  [ComputationBusinessLogic] [varchar](5) NULL,
  [WeeklyCode] [int] NULL,
  [WeeklyDescription] [varchar](80) NULL,
  [LfCode] [int] NULL,
  [LfDescription] [varchar](100) NULL,
  [Schd_Head_No] [int] NULL,
  [Schd_No] [int] NULL,
  [Sub_Schd_No] [int] NULL,
  [Sub_Sub_Schd_No] [int] NULL,
  [SrcSysGLCode] [varchar](50) NULL,
  [SrcSysGLName] [varchar](200) NULL,
  [DestSysGLCode] [varchar](10) NULL,
  [GLCode2] [varchar](10) NULL,
  [GLName2] [varchar](50) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [timestamp],
  [CR_GL_SubGroup] [varchar](100) NULL,
  [CR_GL_Group] [varchar](100) NULL,
  [DR_GL_SubGroup] [varchar](100) NULL,
  [DR_GL_Group] [varchar](100) NULL,
  [LiabilityOrderKey] [smallint] NULL,
  [AssetOrderKey] [smallint] NULL,
  [DR_Flg] [char](1) NULL,
  [CR_Flg] [char](1) NULL,
  [DR_GL_GroupType] [varchar](100) NULL,
  [DR_BS_ScheduleDescription] [varchar](100) NULL,
  [DR_GL_Segment] [varchar](100) NULL,
  [DR_GL_SubSegment] [varchar](100) NULL,
  [CR_GL_GroupType] [varchar](100) NULL,
  [CR_BS_ScheduleDescription] [varchar](100) NULL,
  [CR_GL_Segment] [varchar](100) NULL,
  [CR_GL_SubSegment] [varchar](100) NULL,
  [OA] [tinyint] NULL DEFAULT (NULL),
  [OL] [tinyint] NULL DEFAULT (NULL),
  [Control] [tinyint] NULL DEFAULT (NULL),
  [TDS] [tinyint] NULL DEFAULT (NULL),
  [GST] [tinyint] NULL DEFAULT (NULL)
)
ON [PRIMARY]
GO