CREATE TABLE [dbo].[DerivativeDetail_mod] (
  [EntityKey] [bigint] NOT NULL,
  [DerivativeEntityID] [int] NOT NULL,
  [CustomerACID] [varchar](30) NULL,
  [CustomerID] [varchar](30) NULL,
  [CustomerName] [varchar](100) NULL,
  [DerivativeRefNo] [varchar](30) NULL,
  [Duedate] [date] NULL,
  [DueAmt] [decimal](16, 2) NULL,
  [OsAmt] [decimal](16, 2) NULL,
  [POS] [decimal](16, 2) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](100) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [smalldatetime] NULL,
  [Changefields] [varchar](100) NULL,
  [InstrumentName] [varchar](30) NULL,
  [OverDueSinceDt] [date] NULL,
  [DueAmtReceivable] [decimal](18, 2) NULL,
  [MTMIncomeAmt] [decimal](18, 2) NULL,
  [CouponDate] [date] NULL,
  [CouponAmt] [decimal](18, 2) NULL,
  [CouponOverDueSinceDt] [date] NULL,
  [OverdueCouponAmt] [decimal](18, 2) NULL,
  CHECK ([EffectiveToTimeKey]=(49999)),
  CHECK ([EffectiveToTimeKey]=(49999))
)
ON [PRIMARY]
GO