CREATE TABLE [dbo].[RBL_PUI_DATA] (
  [Customer ID] [nvarchar](255) NULL,
  [Customer Name] [nvarchar](255) NULL,
  [Account ID] [nvarchar](255) NULL,
  [Project Category] [nvarchar](255) NULL,
  [Project Sub Category] [nvarchar](255) NULL,
  [Project Ownership] [nvarchar](255) NULL,
  [Project Authority] [nvarchar](255) NULL,
  [Original DCCO] [datetime] NULL,
  [Original Project cost] [float] NULL,
  [Original Debt] [float] NULL,
  [Revised DCCO] [datetime] NULL,
  [Initial Extenstion] [nvarchar](255) NULL,
  [Beyond control of Promoters] [nvarchar](255) NULL,
  [Court Case Arbitration] [nvarchar](255) NULL,
  [Change in Ownership ] [nvarchar](255) NULL,
  [CIO Reference date] [nvarchar](255) NULL,
  [CIO_DCCO] [datetime] NULL,
  [Change in Project Scope] [nvarchar](255) NULL,
  [Fresh Original DCCO] [nvarchar](255) NULL,
  [Cost Overrun] [nvarchar](255) NULL,
  [Cost overrun Finance by Bank] [nvarchar](255) NULL,
  [Cost Overrun Per] [float] NULL,
  [Revised Project cost] [float] NULL,
  [Revised Debt] [float] NULL,
  [Takeout finance] [nvarchar](255) NULL,
  [Asset class in Sellers book] [nvarchar](255) NULL,
  [Npa Date in Sellers book] [nvarchar](255) NULL,
  [Restructuring] [datetime] NULL,
  [Current Asset Class] [nvarchar](255) NULL,
  [NPA Date] [nvarchar](255) NULL,
  [Actual DCCO] [datetime] NULL,
  [RM_Credit officer] [nvarchar](255) NULL
)
ON [PRIMARY]
GO