CREATE TABLE [dbo].[AccountLevelPreMOC] (
  [EntityKey] [int] IDENTITY,
  [AccountEntityID] [int] NULL,
  [AccountID] [varchar](30) NULL,
  [POS] [decimal](18, 2) NULL,
  [InterestReceivable] [decimal](18, 2) NULL,
  [RestructureFlag] [char](1) NULL,
  [RestructureDate] [date] NULL,
  [FITLFlag] [char](1) NULL,
  [DFVAmount] [decimal](16, 2) NULL,
  [RePossessionFlag] [char](1) NULL,
  [RePossessionDate] [date] NULL,
  [InherentWeaknessFlag] [char](1) NULL,
  [InherentWeaknessDate] [date] NULL,
  [SARFAESIFlag] [char](1) NULL,
  [SARFAESIDate] [date] NULL,
  [UnusualBounceFlag] [char](1) NULL,
  [UnusualBounceDate] [date] NULL,
  [UnclearedEffectsFlag] [char](1) NULL,
  [UnclearedEffectsDate] [date] NULL,
  [AdditionalProvisionCustomerlevel] [decimal](16, 2) NULL,
  [AdditionalProvisionAbsolute] [decimal](16, 2) NULL,
  [MOCReason] [varchar](500) NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [datetime] NULL,
  [ModifyBy] [varchar](100) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [date] NULL,
  [MOCDate] [date] NULL,
  [MOCBy] [varchar](100) NULL,
  [MOCSource] [int] NULL,
  [FraudAccountFlag] [char](1) NULL,
  [FraudDate] [date] NULL,
  [ScreenFlag] [char](1) NULL
)
ON [PRIMARY]
GO