CREATE TABLE [dbo].[IBPCACFlaggingDetail_Mod] (
  [Entity_Key] [int] IDENTITY,
  [AccountFlagAlt_Key] [int] NULL,
  [SourceAlt_Key] [int] NULL,
  [AccountID] [varchar](30) NULL,
  [CustomerID] [varchar](30) NULL,
  [CustomerName] [varchar](30) NULL,
  [FlagAlt_Key] [varchar](30) NULL,
  [PoolID] [varchar](30) NULL,
  [PoolName] [varchar](30) NULL,
  [AccountBalance] [decimal](18, 2) NULL,
  [POS] [decimal](18, 2) NULL,
  [InterestReceivable] [decimal](18, 2) NULL,
  [ExposureAmount] [decimal](18, 2) NULL,
  [IPBCOutDate] [date] NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](50) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [varchar](50) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [timestamp],
  [Remark] [varchar](250) NULL,
  [SourceName] [varchar](50) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [ApprovedByFirstLevel] [varchar](30) NULL,
  [changefields] [varchar](100) NULL,
  [PoolType] [varchar](30) NULL,
  [MaturityDate] [date] NULL,
  [IBPCMarkingDate] [date] NULL
)
ON [PRIMARY]
GO