CREATE TABLE [dbo].[Fraud_Details] (
  [EntityKey] [bigint] IDENTITY,
  [AccountEntityId] [int] NULL,
  [CustomerEntityId] [int] NULL,
  [RefCustomerACID] [varchar](30) NULL,
  [RefCustomerID] [varchar](30) NULL,
  [RFA_ReportingByBank] [varchar](2) NULL,
  [RFA_DateReportingByBank] [date] NULL,
  [RFA_OtherBankAltKey] [char](1) NULL,
  [RFA_OtherBankDate] [date] NULL,
  [FraudOccuranceDate] [date] NULL,
  [FraudDeclarationDate] [date] NULL,
  [FraudNature] [varchar](500) NULL,
  [FraudArea] [varchar](500) NULL,
  [CurrentAssetClassAltKey] [int] NULL,
  [ProvPref] [varchar](20) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](100) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [smalldatetime] NULL,
  [FirstLevelApprovedBy] [varchar](100) NULL,
  [FirstLevelDateApproved] [date] NULL,
  [screenFlag] [char](1) NULL,
  [UploadID] [int] NULL,
  [SrNo] [int] NULL,
  [NPA_DateAtFraud] [date] NULL,
  [AssetClassAtFraudAltKey] [int] NULL,
  [Action] [varchar](max) NULL,
  [ReasonforRFAClassification] [varchar](500) NULL,
  [DateofRemovalofRFAClassification] [date] NULL,
  [ReasonforRemovalofRFAClassification] [varchar](500) NULL,
  [DateofRemovalofRFAClassificationReporting] [date] NULL,
  [RFAReportedOtherBank] [varchar](2) NULL,
  [NameofBank] [varchar](500) NULL,
  [AssetClassAlt_KeyBeforeFruad] [int] NULL,
  [NPADateBeforeFraud] [date] NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO