CREATE TABLE [dbo].[AccountLevelMOC_Mod] (
  [EntityKey] [int] IDENTITY,
  [AccountEntityID] [int] NULL,
  [AccountID] [varchar](30) NULL,
  [POS] [decimal](18, 2) NULL,
  [InterestReceivable] [decimal](18, 2) NULL,
  [RestructureFlag] [char](1) NULL,
  [RestructureDate] [date] NULL,
  [FITLFlag] [char](1) NULL,
  [DFVAmount] [decimal](16, 2) NULL,
  [RePossessionFlag] [char](1) NULL,
  [RePossessionDate] [date] NULL,
  [InherentWeaknessFlag] [char](1) NULL,
  [InherentWeaknessDate] [date] NULL,
  [SARFAESIFlag] [char](1) NULL,
  [SARFAESIDate] [date] NULL,
  [UnusualBounceFlag] [char](1) NULL,
  [UnusualBounceDate] [date] NULL,
  [UnclearedEffectsFlag] [char](1) NULL,
  [UnclearedEffectsDate] [date] NULL,
  [AdditionalProvisionCustomerlevel] [decimal](16, 2) NULL,
  [AdditionalProvisionAbsolute] [decimal](16, 2) NULL,
  [MOCReason] [varchar](500) NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [datetime] NULL,
  [ModifyBy] [varchar](100) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [datetime] NULL,
  [MOCDate] [date] NULL,
  [MOCBy] [varchar](100) NULL,
  [MOCSource] [varchar](50) NULL,
  [FraudAccountFlag] [char](1) NULL,
  [FraudDate] [date] NULL,
  [ScreenFlag] [char](1) NULL,
  [MOCTypeAlt_Key] [int] NULL,
  [ApprovedByFirstLevel] [varchar](100) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [ChangeField] [varchar](max) NULL,
  [UploadID] [int] NULL,
  [SrNo] [int] NULL,
  [FlgTwo] [char](1) NULL,
  [TwoDate] [date] NULL,
  [TwoAmount] [decimal](18, 2) NULL,
  [MOC_TYPEFLAG] [varchar](4) NULL,
  [changefields] [varchar](50) NULL,
  [MOCType] [varchar](50) NULL,
  [AddlProvPer] [decimal](16, 2) NULL,
  [MOC_Reason_Remark] [varchar](150) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO