CREATE TABLE [dbo].[AdvAcPUIDetailSub_mod] (
  [EntityKey] [int] IDENTITY,
  [CustomerID] [varchar](30) NULL,
  [ChangeinProjectScope] [char](1) NULL,
  [FreshOriginalDCCO] [date] NULL,
  [RevisedDCCO] [date] NULL,
  [CourtCaseArbitration] [char](1) NULL,
  [ChangeinOwnerShip] [char](1) NULL,
  [CIOReferenceDate] [date] NULL,
  [CIODCCO] [date] NULL,
  [CostOverRun] [char](1) NULL,
  [RevisedProjectCost] [decimal](16, 2) NULL,
  [RevisedDebt] [decimal](16, 2) NULL,
  [RevisedDebt_EquityRatio] [decimal](16, 2) NULL,
  [TakeOutFinance] [char](1) NULL,
  [AssetClassSellerBookAlt_key] [int] NULL,
  [NPADateSellerBook] [date] NULL,
  [Restructuring] [char](1) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [AccountEntityId] [int] NULL,
  [AccountID] [varchar](50) NULL,
  [InitialExtenstion] [char](1) NULL,
  [ExtnReason_BCP] [char](1) NULL,
  [Npa_date] [date] NULL,
  [Npa_Reason] [varchar](255) NULL,
  [AssetClassAlt_Key] [smallint] NULL,
  [FirstLevelApprovedBy] [varchar](20) NULL,
  [FirstLevelDateApproved] [smalldatetime] NULL,
  [ActualDCCO_Achieved] [char](1) NULL,
  [ActualDCCO_Date] [date] NULL,
  [RM_CreditOfficer] [varchar](100) NULL,
  [changeFields] [varchar](100) NULL
)
ON [PRIMARY]
GO