CREATE TABLE [dbo].[DimGeography] (
  [District_Key] [smallint] NOT NULL,
  [DistrictAlt_Key] [smallint] NOT NULL,
  [DistrictName] [varchar](50) NOT NULL,
  [StateAlt_Key] [smallint] NOT NULL,
  [StateName] [varchar](50) NULL,
  [TerritoryAlt_Key] [smallint] NULL,
  [TerritoryName] [varchar](50) NULL,
  [GeographyShortName] [varchar](20) NULL,
  [GeographyShortNameEnum] [varchar](20) NULL,
  [GeographyGroup] [varchar](50) NULL,
  [GeographySubGroup] [varchar](50) NULL,
  [GeographySegment] [varchar](50) NULL,
  [GeographyValidCode] [char](1) NULL,
  [IdentifiedDist] [varchar](1) NULL,
  [MajorityReligionAlt_Key] [smallint] NULL,
  [SrcSysDistrictCode] [varchar](50) NULL,
  [SrcSysDistrictName] [varchar](50) NULL,
  [DestSysDistrictCode] [varchar](10) NULL,
  [DestSysStateCode] [varchar](10) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [UnderBanked] [char](1) NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifyBy] [varchar](20) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [timestamp],
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL
)
ON [PRIMARY]
GO