CREATE TABLE [dbo].[DimUserInfo] (
  [EntityKey] [int] IDENTITY,
  [UserLoginID] [varchar](20) NULL,
  [UserName] [varchar](50) NULL,
  [LoginPassword] [varchar](max) NULL,
  [PasswordChanged] [char](1) NULL,
  [PasswordChangeDate] [date] NULL,
  [ChangePwdCnt] [smallint] NULL,
  [UserLocation] [varchar](10) NULL,
  [UserLocationCode] [varchar](10) NULL,
  [UserRoleAlt_Key] [smallint] NULL,
  [SuspendedUser] [char](1) NULL,
  [CurrentLoginDate] [date] NULL,
  [ResetDate] [date] NULL,
  [Activate] [char](1) NULL,
  [UserLogged] [bit] NULL,
  [UserDeletionReasonAlt_Key] [int] NULL,
  [SystemLogOut] [bit] NULL,
  [EmployeeID] [varchar](20) NULL,
  [UserType] [varchar](20) NULL,
  [IsEmployee] [char](1) NULL,
  [IsChecker] [char](1) NULL,
  [RBIFLAG] [char](1) NULL,
  [DeptGroupCode] [varchar](10) NULL,
  [Email_ID] [varchar](200) NULL,
  [SecuritQsnAlt_Key] [int] NULL,
  [SecurityAns] [varchar](200) NULL,
  [MenuId] [varchar](max) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifyBy] [varchar](20) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [timestamp],
  [MIS_APP_USR_ID] [varchar](20) NULL,
  [MIS_APP_USR_PASS] [varchar](max) NULL,
  [UserLocationExcel] [varchar](100) NULL,
  [DesignationAlt_Key] [smallint] NULL,
  [MobileNo] [varchar](max) NULL,
  [IsCMA] [char](1) NULL,
  [SSOUse] [char](1) NULL,
  [SessionId] [int] NULL,
  [ProffEntityId] [int] NULL,
  [GradeScaleAlt_Key] [smallint] NULL,
  [EmployeeTypeAlt_Key] [smallint] NULL,
  [IsReport] [char](1) NULL,
  [UserActivationDate] [date] NULL,
  [UserDeactivationDate] [date] NULL,
  [WorkFlowUserRoleAlt_Key] [smallint] NULL,
  [DepartmentId] [int] NULL,
  [ApplicableSolIds] [varchar](max) NULL,
  [ApplicableBACID] [varchar](max) NULL,
  [ScreenFlag] [char](1) NULL,
  [IsChecker2] [varchar](1) NULL,
  [Extension] [varchar](max) NULL,
  [Designation] [varchar](50) NULL,
  [SailPoint] [char](1) NULL,
  [ChangeFields] [varchar](100) NULL,
  [LastRequestTime] [datetime] NULL,
  CONSTRAINT [ck_No_Special_Characters] CHECK (NOT [UserLoginID] like '%[^[^*|\":<>[]{}`\( );@&$]+$]%')
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO