CREATE TABLE [dbo].[SecuritizedFinalACDetail] (
  [EntityKey] [int] IDENTITY,
  [SummaryID] [int] NULL,
  [PoolID] [varchar](max) NULL,
  [PoolName] [varchar](max) NULL,
  [CustomerID] [varchar](max) NULL,
  [AccountID] [varchar](max) NULL,
  [AuthorisationStatus] [varchar](20) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifyBy] [varchar](100) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [ChangeFields] [varchar](100) NULL,
  [POS] [decimal](18, 2) NULL,
  [InterestReceivable] [decimal](18, 2) NULL,
  [SourceAlt_Key] [int] NULL,
  [SourceName] [varchar](30) NULL,
  [CustomerName] [varchar](200) NULL,
  [FlagAlt_Key] [varchar](20) NULL,
  [AccountBalance] [decimal](18, 2) NULL,
  [ExposureAmount] [decimal](18, 2) NULL,
  [Remark] [varchar](200) NULL,
  [SecuritisationType] [varchar](50) NULL,
  [ScrOutDate] [date] NULL,
  [ScrInDate] [date] NULL,
  [poolType] [varchar](30) NULL,
  [MaturityDate] [date] NULL,
  [SecMarkingDate] [date] NULL,
  [InterestAccruedinRs] [decimal](18, 2) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO