CREATE TABLE [dbo].[INVESTMENT_DATA] (
  [Process_Date] [nvarchar](30) NULL,
  [BRANCHCODE] [varchar](10) NULL,
  [ISSUERID] [varchar](30) NULL,
  [ISSUERNAME] [varchar](100) NULL,
  [REF_TXN_SYS_CUST_ID] [varchar](25) NULL,
  [ISSUER_CATEGORY_CODE] [char](3) NULL,
  [UCIFID] [varchar](30) NULL,
  [PANNO] [varchar](10) NULL,
  [INVID] [varchar](30) NULL,
  [ISIN] [varchar](12) NULL,
  [INSTRUMENTTYPENAME] [varchar](100) NULL,
  [INSTRNAME] [varchar](100) NULL,
  [INVESTMENTNATURE] [varchar](25) NULL,
  [EXPOSURETYPE] [varchar](25) NULL,
  [MATURITYDT] [date] NULL,
  [HOLDINGNATURE] [char](3) NULL,
  [BOOKTYPE] [varchar](25) NULL,
  [BOOKVALUE] [decimal](18, 2) NULL,
  [MTMVALUE] [decimal](18, 2) NULL,
  [INTEREST_DIVIDENDDUEDATE] [date] NULL,
  [INTEREST_DIVIDENDDUEAMOUNT] [decimal](16, 2) NULL,
  [DPD] [int] NULL,
  [FLGDEG] [char](1) NULL,
  [DEGREASON] [varchar](500) NULL,
  [FLGUPG] [char](1) NULL,
  [UPGDATE] [date] NULL,
  [TOTALPROVISON] [decimal](18, 2) NULL,
  [ASSETCLASS] [varchar](20) NULL,
  [PartialRedumptionDueDate] [date] NULL,
  [PartialRedumptionSettledY_N] [char](1) NULL
)
ON [PRIMARY]
GO