CREATE TABLE [dbo].[DIMASSETCLASS] (
  [AssetClass_Key] [smallint] IDENTITY,
  [AssetClassAlt_Key] [smallint] NULL,
  [AssetClassSubGroupOrderKey] [tinyint] NULL,
  [AssetClassOrderKey] [tinyint] NULL,
  [AssetClassName] [varchar](50) NULL,
  [AssetClassShortName] [varchar](20) NULL,
  [AssetClassShortNameEnum] [varchar](20) NULL,
  [AssetClassGroup] [varchar](50) NULL,
  [AssetClassSubGroup] [varchar](50) NULL,
  [AssetClassSegment] [varchar](50) NULL,
  [AssetClassValidCode] [char](1) NULL,
  [FinacleAssetClassCode] [varchar](20) NULL,
  [VP_AssetClassCode] [varchar](20) NULL,
  [GanasevaAssetClassCode] [varchar](20) NULL,
  [TradeProAssetClassCode] [varchar](20) NULL,
  [CalypsoAssetClassCode] [varchar](20) NULL,
  [ProlendzAssetClassCode] [varchar](20) NULL,
  [eCBFAssetClassCode] [varchar](20) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [PTSmartAssetClassCode] [varchar](20) NULL,
  [VeefinAssetClassCode] [varchar](20) NULL,
  [Finacle2AssetClassCode] [varchar](20) NULL,
  [ApprovedByFirstLevel] [varchar](100) NULL,
  [DateApprovedFirstLevel] [datetime] NULL
)
ON [PRIMARY]
GO