CREATE TABLE [dbo].[DimState] (
  [State_Key] [smallint] NOT NULL,
  [StateAlt_Key] [smallint] NOT NULL,
  [StateAlt2_Key] [smallint] NOT NULL,
  [StateName] [varchar](50) NOT NULL,
  [StateShortName] [varchar](20) NULL,
  [StateShortNameEnum] [varchar](20) NULL,
  [StateGroup] [varchar](50) NULL,
  [StateSubGroup] [varchar](50) NULL,
  [StateSegment] [varchar](50) NULL,
  [StateValidCode] [char](1) NULL,
  [TerritoryAlt_Key] [smallint] NOT NULL,
  [TerritoryName] [varchar](50) NOT NULL,
  [CibilCode] [varchar](2) NULL,
  [PINCode] [varchar](100) NULL,
  [RBICode] [varchar](2) NULL,
  [CIBIL_COMM_CODE] [varchar](2) NULL,
  [MCAStateCode] [char](2) NULL,
  [OfficialLanguageCatg] [char](1) NULL,
  [SrcSysStateCode] [varchar](50) NULL,
  [SrcSysStateName] [varchar](50) NULL,
  [DestSysStateCode] [varchar](10) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifyBy] [varchar](20) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [timestamp]
)
ON [PRIMARY]
GO