CREATE TABLE [dbo].[MOC_ChangeDetails] (
  [EntityKey] [int] IDENTITY,
  [MOCType_Flag] [varchar](4) NULL,
  [CustomerEntityID] [int] NULL,
  [AccountEntityID] [int] NULL,
  [AssetClassAlt_Key] [smallint] NULL,
  [NPA_Date] [date] NULL,
  [AddlProvPer] [decimal](5, 2) NULL,
  [AddlProvAbs] [decimal](16, 2) NULL,
  [CurntQtrRv] [decimal](16, 2) NULL,
  [PrincOutStd] [decimal](16, 2) NULL,
  [unserviedint] [decimal](16, 2) NULL,
  [FlgRestructure] [char](1) NULL,
  [RestructureDate] [date] NULL,
  [FlgFITL] [char](1) NULL,
  [DFVAmt] [decimal](16, 2) NULL,
  [FlgFraud] [char](1) NULL,
  [FraudDate] [date] NULL,
  [TwoFlag] [char](1) NULL,
  [TwoDate] [date] NULL,
  [MOC_Reason] [varchar](250) NULL,
  [MOC_Date] [date] NULL,
  [MOC_By] [varchar](100) NULL,
  [MOC_Source] [varchar](50) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedByFirstLevel] [varchar](20) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [MOCTYPE] [varchar](10) NULL,
  [TwoAmount] [decimal](18, 2) NULL,
  [MOC_ExpireDate] [date] NULL,
  [MOCReasonRemark] [varchar](500) NULL,
  [MOC_Reason_Remark] [varchar](150) NULL
)
ON [PRIMARY]
GO