CREATE TABLE [dbo].[RP_Portfolio_Details] (
  [EntityKey] [int] IDENTITY,
  [PAN_No] [varchar](12) NULL,
  [UCIC_ID] [varchar](20) NULL,
  [CustomerID] [varchar](20) NULL,
  [CustomerName] [varchar](100) NULL,
  [BankingArrangementAlt_Key] [smallint] NULL,
  [BorrowerDefaultDate] [datetime] NULL,
  [LeadBankAlt_Key] [smallint] NULL,
  [DefaultStatusAlt_Key] [varchar](20) NULL,
  [ExposureBucketAlt_Key] [smallint] NULL,
  [ReferenceDate] [datetime] NULL,
  [ReviewExpiryDate] [datetime] NULL,
  [RP_ApprovalDate] [datetime] NULL,
  [RPNatureAlt_Key] [smallint] NULL,
  [If_Other] [varchar](500) NULL,
  [RP_ExpiryDate] [datetime] NULL,
  [RP_ImplDate] [datetime] NULL,
  [RP_ImplStatusAlt_Key] [smallint] NULL,
  [RP_failed] [char](1) NULL,
  [Revised_RP_Expiry_Date] [datetime] NULL,
  [Actual_Impl_Date] [datetime] NULL,
  [RP_OutOfDateAllBanksDeadline] [datetime] NULL,
  [IsBankExposure] [char](1) NULL,
  [AssetClassAlt_Key] [smallint] NULL,
  [RiskReviewExpiryDate] [datetime] NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [CreatedBy] [varchar](50) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](50) NULL,
  [DateApproved] [smalldatetime] NULL,
  [NameOf1stReportingBanklenderAlt_Key] [smallint] NULL,
  [ICAStatusAlt_Key] [smallint] NULL,
  [ReasonnotsigningICA] [varchar](250) NULL,
  [ICAExecutionDate] [date] NULL,
  [IBCFillingDate] [date] NULL,
  [IBCAddmissionDate] [date] NULL,
  [ScreenFlag] [char](1) NULL,
  [IsActive] [char](1) NULL,
  [ApprovedByFirstLevel] [varchar](100) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [BorrowerPAN] [varchar](15) NULL,
  [RevisedRPDeadline_Altkey] [int] NULL,
  [ChangeField] [varchar](max) NULL,
  [IfRPisRectificationthenRiskReviewTimeline] [datetime] NULL,
  [CustomerEntityID] [int] NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO