CREATE TABLE [dbo].[MetagridAccountMaster] (
  [Date_of_Data] [date] NULL,
  [Source_System_Name] [varchar](30) NULL,
  [Branch_Code] [varchar](10) NULL,
  [Customer_UCIC_ID] [varchar](20) NULL,
  [Customer_ID] [varchar](30) NULL,
  [Customer_Ac_ID] [varchar](30) NULL,
  [Ac_Open_Dt] [date] NULL,
  [Scheme_Type] [varchar](30) NULL,
  [Scheme_Product_Code] [varchar](100) NULL,
  [Ac_Segment_Code] [varchar](100) NULL,
  [Facility_Type] [varchar](10) NULL,
  [GL_Code] [varchar](30) NULL,
  [Sector] [varchar](50) NULL,
  [Purpose_of_Advance] [varchar](100) NULL,
  [Industry_Code] [varchar](50) NULL,
  [First_Dt_Of_Disb] [date] NULL,
  [Intt_Rate] [decimal](4, 2) NULL,
  [Banking_Arrangement] [varchar](50) NULL,
  [Currency_Code] [varchar](10) NULL,
  [Unhedged_FCY_Amount] [decimal](16, 2) NULL,
  [Balance_Outstanding_INR] [decimal](16, 2) NULL,
  [Balance_In_Actual_Ac_Currency] [decimal](16, 2) NULL,
  [Advance_Recovery_Amount] [decimal](16, 2) NULL,
  [Cur_Qtr_Credit] [decimal](16, 2) NULL,
  [Cur_Qtr_Int] [decimal](16, 2) NULL,
  [Current_Limit] [decimal](16) NULL,
  [Current_Limit_Date] [date] NULL,
  [Drawing_Power] [decimal](16) NULL,
  [Adhoc_Amt] [decimal](16) NULL,
  [Adhoc_Date] [date] NULL,
  [Adhoc_Expiry_Date] [date] NULL,
  [Conti_Excess_Date] [date] NULL,
  [Debit_Since_Date] [date] NULL,
  [DFV_Amt] [decimal](16, 2) NULL,
  [Govt_Gty_Amt] [decimal](16, 2) NULL,
  [Int_Not_Serviced_Date] [date] NULL,
  [Last_Credit_Date] [date] NULL,
  [POS_Balance] [decimal](16, 2) NULL,
  [Principal_Overdue_Amt] [decimal](16, 2) NULL,
  [Principal_Over_Due_Since_Dt] [date] NULL,
  [Interest_Overdue_Amt] [decimal](16, 2) NULL,
  [Interest_Over_Due_Since_Dt] [date] NULL,
  [Oth_Charges_Overdue_Amt] [decimal](16, 2) NULL,
  [Oth_Changes_Over_Due_Since_Dt] [date] NULL,
  [Review_Due_Dt] [date] NULL,
  [Limit_Expiry_Date] [date] NULL,
  [Stock_Statement_Dt] [date] NULL,
  [UnApplied_Interest_Amt] [decimal](16, 2) NULL,
  [TWO_Date] [date] NULL,
  [TWO_Amount] [decimal](16, 2) NULL,
  [Asset_Class_Norm] [varchar](50) NULL,
  [AC_Category] [tinyint] NULL,
  [Secured_Status] [varchar](50) NULL,
  [Asset_Class_Code] [varchar](50) NULL,
  [NPA_Date] [date] NULL,
  [DBT_LOS_Date] [date] NULL,
  [STD_Provision_Category] [varchar](50) NULL,
  [Fraud_Committed] [varchar](10) NULL,
  [Fraud_Date] [date] NULL,
  [IsIBPC_Exposure] [varchar](10) NULL,
  [IsSecurtised_Exposure] [char](1) NULL,
  [Ac_RM_Name_ID] [varchar](100) NULL,
  [Ac_TL_Name_ID] [varchar](100) NULL,
  [PUI_Marked] [varchar](10) NULL,
  [RFA_Marked] [varchar](10) NULL,
  [IsNonCoperative] [varchar](10) NULL,
  [Interest_due] [decimal](16, 2) NULL,
  [other_dues] [decimal](16, 2) NULL,
  [penal_due] [decimal](16, 2) NULL,
  [int_receivable_adv] [decimal](16, 2) NULL,
  [penal_int_receivable] [decimal](16, 2) NULL,
  [Accrued_interest] [decimal](16, 2) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](100) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [smalldatetime] NULL,
  [EntityKey] [int] IDENTITY,
  [MetagridEntityId] [int] NULL
)
ON [PRIMARY]
GO