CREATE TABLE [dbo].[DimCountry] (
  [Country_Key] [smallint] NOT NULL,
  [CountryAlt_Key] [smallint] NOT NULL,
  [Country2DigitCode] [varchar](10) NULL,
  [Country3DigitCode] [varchar](10) NULL,
  [CountryName] [varchar](50) NULL,
  [CountryShortName] [varchar](20) NULL,
  [CountryShortNameEnum] [varchar](20) NULL,
  [CountryGroup] [varchar](50) NULL,
  [CountrySubGroup] [varchar](50) NULL,
  [CountrySegment] [varchar](50) NULL,
  [CountryValidCode] [char](1) NULL,
  [CurrencyCode] [varchar](10) NULL,
  [CIBIL_CountryCode] [varchar](3) NULL,
  [MOODYRating] [varchar](10) NULL,
  [SNPRating] [varchar](10) NULL,
  [RegulatorCRAR] [varchar](10) NULL,
  [SrcSysCountryCode] [varchar](10) NULL,
  [SrcSysCountryName] [varchar](50) NULL,
  [DestSysCountryCode] [varchar](10) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModifie] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [timestamp]
)
ON [PRIMARY]
GO