CREATE TABLE [dbo].[InvMOC_ChangeDetails] (
  [EntityKey] [int] IDENTITY,
  [MOCType_Flag] [varchar](10) NULL,
  [UCIC_ID] [varchar](100) NULL,
  [InvID] [varchar](100) NULL,
  [AssetClassAlt_Key] [int] NULL,
  [BookValueINR] [decimal](18, 2) NULL,
  [MTMValue] [decimal](18, 2) NULL,
  [SMA_Dt] [date] NULL,
  [SMA_Class] [varchar](5) NULL,
  [NPA_Date] [date] NULL,
  [AddlProvPer] [decimal](5, 2) NULL,
  [AddlProvAbs] [decimal](16, 2) NULL,
  [SecurityValue] [decimal](16, 2) NULL,
  [FlgRestructure] [char](1) NULL,
  [RestructureDate] [date] NULL,
  [FlgFraud] [char](1) NULL,
  [FraudDate] [date] NULL,
  [MOC_ExpireDate] [date] NULL,
  [MOC_Reason] [varchar](250) NULL,
  [MOC_Date] [date] NULL,
  [MOC_By] [varchar](100) NULL,
  [MOC_Source] [varchar](50) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedByFirstLevel] [varchar](20) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [MOCTYPE] [varchar](10) NULL,
  [MOCProcessed] [varchar](10) NULL
)
ON [PRIMARY]
GO