CREATE TABLE [dbo].[CalypsoInvMOC_ChangeDetails] (
  [EntityKey] [int] IDENTITY,
  [MOCType_Flag] [varchar](4) NULL,
  [CustomerEntityID] [int] NULL,
  [AccountEntityID] [int] NULL,
  [AssetClassAlt_Key] [int] NULL,
  [NPA_Date] [date] NULL,
  [AddlProvPer] [decimal](5, 2) NULL,
  [AddlProvAbs] [decimal](16, 2) NULL,
  [CurntQtrRv] [decimal](16, 2) NULL,
  [PrincOutStd] [decimal](16, 2) NULL,
  [unserviedint] [decimal](16, 2) NULL,
  [FlgRestructure] [char](1) NULL,
  [RestructureDate] [date] NULL,
  [FlgFITL] [char](1) NULL,
  [DFVAmt] [decimal](16, 2) NULL,
  [RePossession] [char](1) NULL,
  [RepossessionDate] [date] NULL,
  [WeakAccount] [char](1) NULL,
  [WeakAccountDate] [date] NULL,
  [Sarfaesi] [char](1) NULL,
  [SarfaesiDate] [date] NULL,
  [FlgUnusualBounce] [char](1) NULL,
  [UnusualBounceDate] [date] NULL,
  [FlgUnClearedEffect] [char](1) NULL,
  [UnClearedEffectDate] [date] NULL,
  [FlgFraud] [char](1) NULL,
  [FraudDate] [date] NULL,
  [BenamiLoansFlag] [char](1) NULL,
  [MarkBenamiDate] [date] NULL,
  [SubLendingFlag] [char](1) NULL,
  [MarkSubLendingDate] [date] NULL,
  [AbscondingFlag] [char](1) NULL,
  [MarkAbscondingDate] [date] NULL,
  [TwoFlag] [char](1) NULL,
  [TwoDate] [date] NULL,
  [MOC_ExpireDate] [date] NULL,
  [MOC_Reason] [varchar](250) NULL,
  [MOC_Date] [date] NULL,
  [MOC_By] [varchar](100) NULL,
  [MOC_Source] [varchar](50) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedByFirstLevel] [varchar](20) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [MOCTYPE] [varchar](10) NULL,
  [TwoAmount] [decimal](18, 2) NULL,
  [MOCProcessed] [varchar](10) NULL,
  [BookValue] [decimal](18, 2) NULL,
  [SMADate] [datetime] NULL,
  [SMASubAssetClassValue] [varchar](30) NULL,
  [UCICID] [varchar](max) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO