CREATE TABLE [dbo].[CutomerLevelMOCSelect_Mod] (
  [Entity_Key] [int] IDENTITY,
  [CustomerID] [varchar](50) NULL,
  [CustomerName] [varchar](100) NULL,
  [CustomerEntityID] [int] NULL,
  [AssetClass] [varchar](20) NULL,
  [AssetClassAlt_Key] [int] NULL,
  [NPADate] [date] NULL,
  [SecurityValue] [decimal](18, 2) NULL,
  [AdditionalProvision] [decimal](16, 2) NULL,
  [FraudAccountFlagAlt_Key] [int] NULL,
  [FraudDate] [date] NULL,
  [MOCTypeAlt_Key] [int] NULL,
  [MOCType] [varchar](50) NULL,
  [MOCReason] [smallint] NULL,
  [MOCDate] [smalldatetime] NULL,
  [MOCBy] [varchar](50) NULL,
  [DateOfDate] [date] NULL,
  [Level1ApprovedBy] [varchar](50) NULL,
  [Level2ApprovedBy] [varchar](50) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [AuthorisationStatus] [varchar](5) NULL,
  [CreatedBy] [varchar](50) NULL,
  [DateCreated] [date] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](50) NULL,
  [DateApproved] [date] NULL
)
ON [PRIMARY]
GO