CREATE TABLE [dbo].[DimSecurity] (
  [Security_Key] [smallint] NOT NULL,
  [SecurityAlt_Key] [smallint] NOT NULL,
  [SecurityName] [varchar](100) NULL,
  [SecurityShortName] [varchar](20) NULL,
  [SecurityShortNameEnum] [varchar](20) NULL,
  [SecurityGroup] [varchar](50) NULL,
  [SecuritySubGroup] [varchar](50) NULL,
  [SecuritySegment] [varchar](50) NULL,
  [SecurityValidCode] [char](1) NULL,
  [SecurityCRM] [char](1) NULL,
  [SecurityFixedAsset] [char](1) NULL,
  [AssetClass] [varchar](20) NULL,
  [SecurityType] [varchar](10) NULL,
  [CurrencyType] [varchar](10) NULL,
  [RVPresentCheck] [char](1) NULL,
  [CIBILSecurityCode] [varchar](10) NULL,
  [BaselSecurityCRM] [char](1) NULL,
  [SrcSysSecurityCode] [varchar](50) NULL,
  [SrcSysSecurityName] [varchar](50) NULL,
  [SrcSysSecurityCode1] [varchar](50) NULL,
  [SrcSysSecurityName1] [varchar](50) NULL,
  [DestSysSecurityCode] [varchar](15) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModifie] [datetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [timestamp],
  [IRBCollType] [varchar](20) NULL,
  [IRBMark] [varchar](20) NULL
)
ON [PRIMARY]
GO