CREATE TABLE [PRO].[AdvAcRestructureCal_Hist] (
  [EntityKey] [bigint] IDENTITY,
  [AccountEntityId] [int] NULL,
  [AssetClassAlt_KeyOnInvocation] [smallint] NULL,
  [PreRestructureAssetClassAlt_Key] [smallint] NULL,
  [PreRestructureNPA_Date] [date] NULL,
  [ProvPerOnRestrucure] [decimal](5, 2) NULL,
  [RestructureTypeAlt_Key] [smallint] NULL,
  [COVID_OTR_CatgAlt_Key] [smallint] NULL,
  [RestructureDt] [date] NULL,
  [SP_ExpiryDate] [date] NULL,
  [DPD_AsOnRestructure] [smallint] NULL,
  [RestructureFailureDate] [date] NULL,
  [DPD_Breach_Date] [date] NULL,
  [ZeroDPD_Date] [date] NULL,
  [SP_ExpiryExtendedDate] [date] NULL,
  [CurrentPOS] [decimal](20, 2) NULL,
  [CurrentTOS] [decimal](20, 2) NULL,
  [RestructurePOS] [decimal](20, 2) NULL,
  [Res_POS_to_CurrentPOS_Per] [decimal](5, 2) NULL,
  [CurrentDPD] [smallint] NULL,
  [TotalDPD] [smallint] NULL,
  [VDPD] [smallint] NULL,
  [AddlProvPer] [decimal](5, 2) NULL,
  [ProvReleasePer] [decimal](5, 2) NULL,
  [AppliedNormalProvPer] [decimal](5, 2) NULL,
  [FinalProvPer] [decimal](5, 2) NULL,
  [PreDegProvPer] [decimal](5, 2) NULL,
  [UpgradeDate] [date] NULL,
  [SurvPeriodEndDate] [date] NULL,
  [DegDurSP_PeriodProvPer] [decimal](5, 2) NULL,
  [NonFinDPD] [smallint] NULL,
  [InitialAssetClassAlt_Key] [smallint] NULL,
  [FinalAssetClassAlt_Key] [smallint] NULL,
  [RestructureProvision] [decimal](18, 2) NULL,
  [SecuredProvision] [decimal](18, 2) NULL,
  [UnSecuredProvision] [decimal](18, 2) NULL,
  [FlgDeg] [char](1) NULL,
  [FlgUpg] [char](1) NULL,
  [DegDate] [date] NULL,
  [RC_Pending] [char](1) NULL,
  [FinalNpaDt] [date] NULL,
  [RestructureStage] [varchar](50) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [D2Ktimestamp] [timestamp],
  [DegReason] [varchar](100) NULL,
  [InvestmentGrade] [char](1) NULL,
  [POS_10PerPaidDate] [date] NULL,
  [DPD_MaxNonFin] [smallint] NULL,
  [DPD_MaxFin] [smallint] NULL,
  [FlgMorat] [varchar](5) NULL,
  [PreRestructureNPA_Prov] [decimal](5, 2) NULL,
  [RestructureFacilityTypeAlt_Key] [smallint] NULL,
  [IsChanged] [char](1) NULL,
  [EntityKeyNew] [int] NULL,
  [CrntQtrAssetClass] [int] NULL,
  [PrevQtrAssetClass] [int] NULL,
  [MonitoringPeriodStatus] [varchar](50) NULL,
  [SpecifiedPeriodStatus] [varchar](50) NULL,
  [PrevQtrTotalProvision] [decimal](18, 2) NULL,
  [TOTAL_DPD] [int] NULL,
  [NCIF_ID] [varchar](50) NULL,
  [DPD_30_90_Breach_Date] [varchar](50) NULL,
  [TEN_PC_DATE] [date] NULL,
  [SecondRestrDate] [date] NULL,
  [AggregateExposure] [decimal](18, 2) NULL,
  [CreditRating1] [varchar](50) NULL,
  [CreditRating2] [varchar](50) NULL
)
ON [PRIMARY]
GO