CREATE TABLE [PRO].[accountcal_bkp] (
  [EntityKey] [bigint] IDENTITY,
  [AccountEntityID] [int] NULL,
  [UcifEntityID] [int] NULL,
  [CustomerEntityID] [int] NULL,
  [CustomerAcID] [varchar](30) NULL,
  [RefCustomerID] [varchar](50) NULL,
  [SourceSystemCustomerID] [varchar](50) NULL,
  [UCIF_ID] [varchar](50) NULL,
  [BranchCode] [varchar](20) NULL,
  [FacilityType] [varchar](10) NULL,
  [AcOpenDt] [date] NULL,
  [FirstDtOfDisb] [date] NULL,
  [ProductAlt_Key] [int] NULL,
  [SchemeAlt_key] [int] NULL,
  [SubSectorAlt_Key] [int] NULL,
  [SplCatg1Alt_Key] [int] NULL,
  [SplCatg2Alt_Key] [int] NULL,
  [SplCatg3Alt_Key] [int] NULL,
  [SplCatg4Alt_Key] [int] NULL,
  [SourceAlt_Key] [tinyint] NULL,
  [ActSegmentCode] [varchar](10) NULL,
  [InttRate] [decimal](16, 8) NULL,
  [Balance] [decimal](16, 2) NULL,
  [BalanceInCrncy] [decimal](16, 2) NULL,
  [CurrencyAlt_Key] [int] NULL,
  [DrawingPower] [decimal](16, 2) NULL,
  [CurrentLimit] [decimal](16, 2) NULL,
  [CurrentLimitDt] [date] NULL,
  [ContiExcessDt] [date] NULL,
  [StockStDt] [date] NULL,
  [DebitSinceDt] [date] NULL,
  [LastCrDate] [date] NULL,
  [PreQtrCredit] [decimal](16, 2) NULL,
  [PrvQtrInt] [decimal](16, 2) NULL,
  [CurQtrCredit] [decimal](16, 2) NULL,
  [CurQtrInt] [decimal](16, 2) NULL,
  [InttServiced] [char](1) NULL,
  [IntNotServicedDt] [date] NULL,
  [OverdueAmt] [decimal](18, 2) NULL,
  [OverDueSinceDt] [date] NULL,
  [ReviewDueDt] [date] NULL,
  [SecurityValue] [decimal](24) NULL,
  [DFVAmt] [decimal](16, 2) NULL,
  [GovtGtyAmt] [decimal](16, 2) NULL,
  [CoverGovGur] [decimal](16, 2) NULL,
  [WriteOffAmount] [decimal](16, 2) NULL,
  [UnAdjSubSidy] [decimal](16, 2) NULL,
  [CreditsinceDt] [date] NULL,
  [DegReason] [varchar](max) NULL,
  [Asset_Norm] [varchar](15) NULL,
  [REFPeriodMax] [int] NULL,
  [RefPeriodOverdue] [smallint] NULL,
  [RefPeriodOverDrawn] [smallint] NULL,
  [RefPeriodNoCredit] [smallint] NULL,
  [RefPeriodIntService] [smallint] NULL,
  [RefPeriodStkStatement] [smallint] NULL,
  [RefPeriodReview] [smallint] NULL,
  [NetBalance] [decimal](16, 2) NULL,
  [ApprRV] [decimal](22, 2) NULL,
  [SecuredAmt] [decimal](16, 2) NULL,
  [UnSecuredAmt] [decimal](16, 2) NULL,
  [ProvDFV] [decimal](16, 2) NULL,
  [Provsecured] [decimal](16, 2) NULL,
  [ProvUnsecured] [decimal](16, 2) NULL,
  [ProvCoverGovGur] [decimal](16, 2) NULL,
  [AddlProvision] [decimal](16, 2) NULL,
  [TotalProvision] [decimal](16, 2) NULL,
  [BankProvsecured] [decimal](16, 2) NULL,
  [BankProvUnsecured] [decimal](16, 2) NULL,
  [BankTotalProvision] [decimal](16, 2) NULL,
  [RBIProvsecured] [decimal](18, 2) NULL,
  [RBIProvUnsecured] [decimal](18, 2) NULL,
  [RBITotalProvision] [decimal](18, 2) NULL,
  [InitialNpaDt] [date] NULL,
  [FinalNpaDt] [date] NULL,
  [SMA_Dt] [date] NULL,
  [UpgDate] [date] NULL,
  [InitialAssetClassAlt_Key] [int] NULL,
  [FinalAssetClassAlt_Key] [int] NULL,
  [ProvisionAlt_Key] [int] NULL,
  [PNPA_Reason] [varchar](max) NULL,
  [SMA_Class] [varchar](5) NULL,
  [SMA_Reason] [varchar](max) NULL,
  [FlgMoc] [char](1) NULL,
  [MOC_Dt] [date] NULL,
  [CommonMocTypeAlt_Key] [smallint] NULL,
  [FlgDeg] [char](1) NULL,
  [FlgDirtyRow] [char](1) NULL,
  [FlgInMonth] [char](1) NULL,
  [FlgSMA] [char](1) NULL,
  [FlgPNPA] [char](1) NULL,
  [FlgUpg] [char](1) NULL,
  [FlgFITL] [char](1) NULL,
  [FlgAbinitio] [char](1) NULL,
  [NPA_Days] [int] NULL,
  [RefPeriodOverdueUPG] [smallint] NULL,
  [RefPeriodOverDrawnUPG] [smallint] NULL,
  [RefPeriodNoCreditUPG] [smallint] NULL,
  [RefPeriodIntServiceUPG] [smallint] NULL,
  [RefPeriodStkStatementUPG] [smallint] NULL,
  [RefPeriodReviewUPG] [smallint] NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [AppGovGur] [decimal](18, 2) NULL,
  [UsedRV] [decimal](18, 2) NULL,
  [ComputedClaim] [decimal](22, 2) NULL,
  [UPG_RELAX_MSME] [char](1) NULL,
  [DEG_RELAX_MSME] [char](1) NULL,
  [PNPA_DATE] [date] NULL,
  [NPA_Reason] [varchar](max) NULL,
  [PnpaAssetClassAlt_key] [int] NULL,
  [DisbAmount] [decimal](18, 2) NULL,
  [PrincOutStd] [decimal](18, 2) NULL,
  [PrincOverdue] [decimal](18, 2) NULL,
  [PrincOverdueSinceDt] [date] NULL,
  [IntOverdue] [decimal](18, 2) NULL,
  [IntOverdueSinceDt] [date] NULL,
  [OtherOverdue] [decimal](18, 2) NULL,
  [OtherOverdueSinceDt] [date] NULL,
  [RelationshipNumber] [varchar](30) NULL,
  [AccountFlag] [varchar](20) NULL,
  [CommercialFlag_AltKey] [smallint] NULL,
  [Liability] [varchar](20) NULL,
  [CD] [varchar](20) NULL,
  [AccountStatus] [varchar](20) NULL,
  [AccountBlkCode1] [varchar](25) NULL,
  [AccountBlkCode2] [varchar](25) NULL,
  [ExposureType] [varchar](50) NULL,
  [Mtm_Value] [decimal](18, 2) NULL,
  [BankAssetClass] [varchar](10) NULL,
  [NpaType] [varchar](10) NULL,
  [SecApp] [char](1) NULL,
  [BorrowerTypeID] [int] NULL,
  [LineCode] [varchar](30) NULL,
  [ProvPerSecured] [decimal](10, 4) NULL,
  [ProvPerUnSecured] [decimal](10, 4) NULL,
  [MOCReason] [varchar](500) NULL,
  [AddlProvisionPer] [decimal](6, 2) NULL,
  [FlgINFRA] [char](1) NULL,
  [RepossessionDate] [date] NULL,
  [DerecognisedInterest1] [decimal](14) NULL,
  [DerecognisedInterest2] [decimal](14) NULL,
  [ProductCode] [varchar](20) NULL,
  [FlgLCBG] [char](1) NULL,
  [UnserviedInt] [decimal](18, 2) NULL,
  [OriginalBranchcode] [varchar](10) NULL,
  [AdvanceRecovery] [decimal](16, 2) NULL,
  [NotionalInttAmt] [decimal](16, 2) NULL,
  [PrvAssetClassAlt_Key] [int] NULL,
  [MOCTYPE] [varchar](15) NULL,
  [FlgSecured] [char](1) NULL,
  [DPD_IntService] [int] NULL,
  [DPD_NoCredit] [int] NULL,
  [DPD_Overdrawn] [int] NULL,
  [DPD_Overdue] [int] NULL,
  [DPD_Renewal] [int] NULL,
  [DPD_StockStmt] [int] NULL,
  [DPD_Max] [int] NULL,
  [DPD_FinMaxType] [varchar](50) NULL,
  [DPD_SMA] [int] NULL,
  [DPD_PrincOverdue] [int] NULL,
  [DPD_IntOverdueSince] [int] NULL,
  [DPD_OtherOverdueSince] [int] NULL,
  [RePossession] [char](1) NULL,
  [RCPending] [char](1) NULL,
  [PaymentPending] [char](1) NULL,
  [WheelCase] [char](1) NULL,
  [CustomerLevelMaxPer] [decimal](5, 2) NULL,
  [FinalProvisionPer] [decimal](5, 2) NULL,
  [IsIBPC] [char](1) NULL,
  [IsSecuritised] [char](1) NULL,
  [RFA] [char](1) NULL,
  [IsNonCooperative] [char](1) NULL,
  [Sarfaesi] [char](1) NULL,
  [WeakAccount] [char](1) NULL,
  [PUI] [char](1) NULL,
  [FlgFraud] [char](1) NULL,
  [FlgRestructure] [char](1) NULL,
  [RestructureDate] [date] NULL,
  [SarfaesiDate] [date] NULL,
  [FlgUnusualBounce] [char](1) NULL,
  [UnusualBounceDate] [date] NULL,
  [FlgUnClearedEffect] [char](1) NULL,
  [UnClearedEffectDate] [date] NULL,
  [FraudDate] [date] NULL,
  [WeakAccountDate] [date] NULL,
  [IsChanged] [char](1) NULL,
  [EntityKeyNew] [bigint] NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO